Repository CAKK-DEV/cakk-server, pull requests merged in 2024-06, with the labels that each got.

#53 Refactor: 위치 기반 케이크 샵 검색을 위한 리팩토링
  cakk-api/build.gradle
  cakk-api/src/main/java/com/cakk/api/annotation/OperationDays.java
  cakk-api/src/main/java/com/cakk/api/mapper/PointMapper.java
  cakk-api/src/main/java/com/cakk/api/mapper/ShopMapper.java
  cakk-api/src/main/java/com/cakk/api/service/slack/SlackService.java
  cakk-api/src/main/java/com/cakk/api/validator/OperationValidator.java
  cakk-api/src/main/resources/application.yml
  cakk-api/src/test/java/com/cakk/api/common/base/IntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/common/base/ServiceTest.java
  cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/service/shop/ShopServiceTest.java
  cakk-api/src/test/resources/sql/insert-cake-shop.sql
  cakk-api/src/test/resources/sql/insert-cake.sql
  cakk-domain/mysql/build.gradle
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/shop/CakeShopInfoParam.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/cake/CakeTag.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/shop/CakeShop.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/user/BusinessInformation.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/event/EventMapper.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/event/shop/CertificationEvent.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeShopQueryRepository.java
  cakk-domain/mysql/src/test/java/com/cakk/domain/base/DomainTest.java
  cakk-domain/mysql/src/test/java/com/cakk/domain/entity/user/BusinessInformationTest.java
Labels: refactor, test

#54 Feature: 토큰 재발급 로직 작성
  cakk-api/src/main/java/com/cakk/api/annotation/RefreshToken.java
  cakk-api/src/main/java/com/cakk/api/config/WebMvcConfig.java
  cakk-api/src/main/java/com/cakk/api/controller/user/SignController.java
  cakk-api/src/main/java/com/cakk/api/provider/jwt/JwtProvider.java
  cakk-api/src/main/java/com/cakk/api/resolver/RefreshTokenResolver.java
  cakk-api/src/main/java/com/cakk/api/service/user/UserService.java
  cakk-api/src/main/resources/application.yml
  cakk-api/src/test/java/com/cakk/api/common/container/RedisTestContainer.java
  cakk-api/src/test/java/com/cakk/api/integration/user/SignIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/service/user/UserServiceTest.java
  cakk-api/src/test/resources/application-test.yml
  cakk-common/src/main/java/com/cakk/common/enums/ReturnCode.java
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/config/RedisConfig.java
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/impl/TokenRedisRepository.java
Labels: feature

#56 Hotfix: DDL 수정
  cakk-api/src/main/resources/application.yml
Labels: hotfix

#58 Hotfix: prod 환경에서 DDL update로 수정
  cakk-api/src/main/resources/application.yml
Labels: hotfix

#61 Feature: 유저 프로필 수정 기능 구현
  cakk-api/src/main/java/com/cakk/api/config/SecurityConfig.java
  cakk-api/src/main/java/com/cakk/api/controller/user/MyPageController.java
  cakk-api/src/main/java/com/cakk/api/controller/user/SignController.java
  cakk-api/src/main/java/com/cakk/api/controller/user/UserController.java
  cakk-api/src/main/java/com/cakk/api/dto/request/user/ProfileUpdateRequest.java
  cakk-api/src/main/java/com/cakk/api/mapper/UserMapper.java
  cakk-api/src/main/java/com/cakk/api/service/user/SignService.java
  cakk-api/src/main/java/com/cakk/api/service/user/UserService.java
  cakk-api/src/test/java/com/cakk/api/common/base/IntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/integration/user/MyPageIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/integration/user/SignIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/service/user/SignServiceTest.java
  cakk-api/src/test/java/com/cakk/api/service/user/UserServiceTest.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/user/ProfileUpdateParam.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/user/User.java
Labels: feature, test

#63 Feature: 유저 탈퇴 구현
  cakk-api/src/main/java/com/cakk/api/controller/user/MyPageController.java
  cakk-api/src/main/java/com/cakk/api/mapper/UserMapper.java
  cakk-api/src/main/java/com/cakk/api/service/user/UserService.java
  cakk-api/src/test/java/com/cakk/api/integration/user/MyPageIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/service/user/UserServiceTest.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/user/UserWithdrawal.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/jpa/BusinessInformationJpaRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/jpa/CakeLikeJpaRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/jpa/CakeShopLikeJpaRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/jpa/UserWithdrawalJpaRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/writer/BusinessInformationWriter.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/writer/CakeLikeWriter.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/writer/CakeShopLikeWriter.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/writer/UserWriter.java
Labels: feature, test

#64 Feature: 인기 검색어 조회 비즈니스 구현
  cakk-api/src/main/java/com/cakk/api/dto/request/search/TopSearchedListRequest.java
  cakk-api/src/main/java/com/cakk/api/dto/response/search/TopSearchedListResponse.java
  cakk-api/src/main/java/com/cakk/api/mapper/SearchMapper.java
  cakk-api/src/main/java/com/cakk/api/service/search/KeywordService.java
  cakk-api/src/main/java/com/cakk/api/service/user/SignService.java
  cakk-api/src/test/java/com/cakk/api/integration/user/SignIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/service/search/KeywordServiceTest.java
  cakk-api/src/test/java/com/cakk/api/service/user/SignServiceTest.java
  cakk-common/src/main/java/com/cakk/common/enums/RedisKey.java
  cakk-domain/redis/build.gradle
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/annotation/RedisCustomTemplate.java
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/KeywordRedisRepository.java
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/RedisSetRepository.java
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/TokenRedisRepository.java
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/template/RedisValueTemplate.java
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/template/RedisZSetTemplate.java
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/template/impl/RedisStringValueTemplate.java
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/template/impl/RedisStringZSetTemplate.java
Labels: chore, feature, refactor, test

#67 Feature: 사용자 위치 기반 케이크샵 조회
  cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
  cakk-api/src/main/java/com/cakk/api/dto/request/shop/SearchShopByLocationRequest.java
  cakk-api/src/main/java/com/cakk/api/dto/response/shop/CakeShopByMapResponse.java
  cakk-api/src/main/java/com/cakk/api/mapper/ShopMapper.java
  cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
  cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
  cakk-api/src/test/resources/sql/insert-cake-shop.sql
  cakk-api/src/test/resources/sql/insert-cake.sql
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/bo/CakeShopByMaps.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/shop/CakeShopMapParam.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/jpa/CakeShopJpaRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeQueryRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeReader.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeShopReader.java
Labels: feature

#68 Feature: 케이크 검색 기능 추가
  cakk-api/src/main/java/com/cakk/api/controller/cake/CakeController.java
  cakk-api/src/main/java/com/cakk/api/dto/request/cake/CakeImageSearchRequest.java
  cakk-api/src/main/java/com/cakk/api/service/cake/CakeService.java
  cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/cake/CakeSearchParam.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeQueryRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeTagQueryRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeReader.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeTagReader.java
Labels: feature

#73 Feature: 좋아요 한 케이크 목록 조회 구현
  cakk-api/src/main/java/com/cakk/api/controller/cake/CakeController.java
  cakk-api/src/main/java/com/cakk/api/controller/user/MyPageController.java
  cakk-api/src/main/java/com/cakk/api/dto/request/cake/CakeSearchByLocationRequest.java
  cakk-api/src/main/java/com/cakk/api/dto/request/like/LikeCakeSearchRequest.java
  cakk-api/src/main/java/com/cakk/api/dto/response/cake/CakeImageListResponse.java
  cakk-api/src/main/java/com/cakk/api/dto/response/like/LikeCakeImageListResponse.java
  cakk-api/src/main/java/com/cakk/api/mapper/CakeMapper.java
  cakk-api/src/main/java/com/cakk/api/service/cake/CakeService.java
  cakk-api/src/main/java/com/cakk/api/service/like/LikeService.java
  cakk-api/src/test/java/com/cakk/api/common/base/IntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/common/base/ServiceTest.java
  cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/integration/user/LikeIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/integration/user/MyPageIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/service/like/LikeServiceTest.java
  cakk-api/src/test/resources/sql/insert-like.sql
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/like/LikeCakeImageResponseParam.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeLikeQueryRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeQueryRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeLikeReader.java
Labels: feature, refactor

#75 Feature: 케이크 좋아요 기능 구현
  cakk-api/src/main/java/com/cakk/api/service/like/LikeService.java
  cakk-api/src/test/java/com/cakk/api/service/like/LikeServiceTest.java
  cakk-common/src/main/java/com/cakk/common/enums/RedisKey.java
  cakk-common/src/main/java/com/cakk/common/enums/ReturnCode.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/cake/Cake.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/jpa/CakeLikeJpaRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeLikeReader.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/writer/CakeLikeWriter.java
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/LockRedisRepository.java
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/template/RedisValueTemplate.java
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/template/impl/RedisStringValueTemplate.java
Labels: feature

#76 Feature: 케이크 좋아요 API 구현 및 테스트 작성
  .github/workflows/prod-app-api-cd.yml
  cakk-api/src/main/java/com/cakk/api/controller/cake/CakeController.java
  cakk-api/src/main/java/com/cakk/api/service/like/LikeService.java
  cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/service/like/LikeConcurrencyTest.java
  cakk-api/src/test/java/com/cakk/api/service/like/LikeServiceTest.java
  cakk-api/src/test/resources/sql/insert-like-for-concurrency-test.sql
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/UserReader.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/writer/CakeLikeWriter.java
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/LockRedisRepository.java
Labels: feature, test

#83 Fix: 케이크 검색 조회 오류 수정
  cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.java
  cakk-api/src/test/resources/sql/insert-cake.sql
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeQueryRepository.java
Labels: fix

#85 Refactor: Like → Heart 로 네이밍 수정
  cakk-api/src/main/java/com/cakk/api/controller/cake/CakeController.java
  cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
  cakk-api/src/main/java/com/cakk/api/controller/user/MyPageController.java
  cakk-api/src/main/java/com/cakk/api/dto/request/like/HeartCakeSearchRequest.java
  cakk-api/src/main/java/com/cakk/api/dto/response/like/HeartCakeImageListResponse.java
  cakk-api/src/main/java/com/cakk/api/dto/response/like/LikeCakeImageListResponse.java
  cakk-api/src/main/java/com/cakk/api/mapper/CakeMapper.java
  cakk-api/src/main/java/com/cakk/api/service/like/HeartService.java
  cakk-api/src/main/java/com/cakk/api/service/like/LikeService.java
  cakk-api/src/main/java/com/cakk/api/service/user/UserService.java
  cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/integration/user/HeartIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/service/like/HeartConcurrencyTest.java
  cakk-api/src/test/java/com/cakk/api/service/like/HeartServiceTest.java
  cakk-api/src/test/java/com/cakk/api/service/like/LikeServiceTest.java
  cakk-api/src/test/java/com/cakk/api/service/user/UserServiceTest.java
  cakk-api/src/test/resources/sql/delete-all.sql
  cakk-api/src/test/resources/sql/insert-cake-shop.sql
  cakk-api/src/test/resources/sql/insert-cake.sql
  cakk-api/src/test/resources/sql/insert-heart-for-concurrency-test.sql
  cakk-api/src/test/resources/sql/insert-heart.sql
  cakk-common/src/main/java/com/cakk/common/enums/RedisKey.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/like/HeartCakeImageResponseParam.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/cake/Cake.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/cake/CakeHeart.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/shop/CakeShop.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/shop/CakeShopHeart.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/jpa/CakeHeartJpaRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/jpa/CakeShopHeartJpaRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/jpa/CakeShopLikeJpaRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeHeartQueryRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeQueryRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeHeartReader.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeLikeReader.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeShopHeartReader.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeShopLikeReader.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/writer/CakeHeartWriter.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/writer/CakeLikeWriter.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/writer/CakeShopHeartWriter.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/writer/CakeShopLikeWriter.java
Labels: refactor

#90 Feature: 케이크 샵 기본 정보 수정 기능 추가
  cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
  cakk-api/src/main/java/com/cakk/api/dto/request/shop/UpdateShopRequest.java
  cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
  cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
  cakk-common/src/main/java/com/cakk/common/enums/ReturnCode.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/shop/CakeShopUpdateParam.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/shop/CakeShop.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeShopQueryRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeShopReader.java
Labels: feature

#93 Refactor: 분산 락 관련 리팩토링
  cakk-api/build.gradle
  cakk-api/src/main/java/com/cakk/api/annotation/DistributedLock.java
  cakk-api/src/main/java/com/cakk/api/aspect/AopForTransaction.java
  cakk-api/src/main/java/com/cakk/api/aspect/DistributedLockAspect.java
  cakk-api/src/main/java/com/cakk/api/config/AspectConfig.java
  cakk-api/src/main/java/com/cakk/api/controller/cake/CakeController.java
  cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
  cakk-api/src/main/java/com/cakk/api/service/like/HeartService.java
  cakk-api/src/test/java/com/cakk/api/service/like/HeartConcurrencyTest.java
  cakk-api/src/test/java/com/cakk/api/service/like/HeartServiceTest.java
  cakk-common/src/main/java/com/cakk/common/enums/RedisKey.java
  cakk-domain/redis/build.gradle
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/config/RedisConfig.java
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/dto/param/ExecuteWithLockParam.java
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/LockRedisRepository.java
Labels: feature, refactor

#92 Feature: 케이크 샵 외부 링크 수정 기능 추가
  cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
  cakk-api/src/main/java/com/cakk/api/dto/request/link/UpdateLinkRequest.java
  cakk-api/src/main/java/com/cakk/api/mapper/LinkMapper.java
  cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
  cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
  cakk-domain/mysql/build.gradle
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/link/UpdateLinkParam.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/shop/CakeShop.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/shop/CakeShopLink.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeShopQueryRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeShopReader.java
  cakk-domain/mysql/src/test/java/com/cakk/domain/entity/user/BusinessInformationTest.java
Labels: feature

#96 Hotfix: 이미지 업로드를 위한 presigned url 생성 방법 수정
  cakk-external/src/main/java/com/cakk/external/service/S3Service.java
Labels: hotfix

#97 Feature: 케이크 샵 영업일 및 주소 업데이트 기능 추가
  cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
  cakk-api/src/main/java/com/cakk/api/dto/request/operation/ShopOperationParam.java
  cakk-api/src/main/java/com/cakk/api/dto/request/operation/UpdateShopOperationRequest.java
  cakk-api/src/main/java/com/cakk/api/dto/request/shop/UpdateShopAddressRequest.java
  cakk-api/src/main/java/com/cakk/api/mapper/ShopOperationMapper.java
  cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
  cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/operation/UpdateShopOperationParam.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/shop/UpdateShopAddressParam.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/shop/CakeShop.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/shop/CakeShopOperation.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/jpa/CakeShopJpaRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeShopQueryRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeShopReader.java
Labels: feature

#98 Feature: 케이크 수정, 삭제 기능 추가
  cakk-api/src/main/java/com/cakk/api/controller/cake/CakeController.java
  cakk-api/src/main/java/com/cakk/api/dto/request/cake/CakeUpdateRequest.java
  cakk-api/src/main/java/com/cakk/api/mapper/CakeDesignCategoryMapper.java
  cakk-api/src/main/java/com/cakk/api/service/cake/CakeService.java
  cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.java
  cakk-api/src/test/resources/sql/insert-cake.sql
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/cake/CakeUpdateParam.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/cake/Cake.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/cake/CakeCategory.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/cake/CakeTag.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/cake/Tag.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/mapper/CakeTagMapper.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/mapper/TagMapper.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/jpa/TagJpaRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeQueryRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeReader.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/TagReader.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/writer/CakeWriter.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/writer/TagWriter.java
Labels: feature

#100 Feature: 케이크 샵 좋아요 목록 조회 구현
  cakk-api/src/main/java/com/cakk/api/controller/user/MyPageController.java
  cakk-api/src/main/java/com/cakk/api/dto/request/like/HeartCakeShopSearchRequest.java
  cakk-api/src/main/java/com/cakk/api/dto/response/like/HeartCakeShopListResponse.java
  cakk-api/src/main/java/com/cakk/api/mapper/ShopMapper.java
  cakk-api/src/main/java/com/cakk/api/service/like/HeartService.java
  cakk-api/src/test/java/com/cakk/api/integration/user/HeartIntegrationTest.java
  cakk-api/src/test/resources/sql/insert-cake.sql
  cakk-api/src/test/resources/sql/insert-heart.sql
  cakk-common/src/main/java/com/cakk/common/utils/SetUtils.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/like/HeartCakeShopResponseParam.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeShopHeartQueryRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeHeartReader.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeShopHeartReader.java
Labels: feature

#104 Feature: 케이크 조회수 증가 이벤트 리스닝 구현
  cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
  cakk-api/src/main/java/com/cakk/api/listener/shop/CertificationEventListener.java
  cakk-api/src/main/java/com/cakk/api/listener/views/ViewsIncreaseEventListener.java
  cakk-api/src/main/java/com/cakk/api/service/views/ViewsService.java
  cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/cake/Cake.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/event/EventMapper.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/event/views/CakeIncreaseViewsEvent.java
Labels: feature, test

#106 Feature: 케이크 및 케이크샵 하트 여부 조회 구현
  cakk-api/src/main/java/com/cakk/api/controller/cake/CakeController.java
  cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
  cakk-api/src/main/java/com/cakk/api/dto/response/like/HeartResponse.java
  cakk-api/src/main/java/com/cakk/api/mapper/HeartMapper.java
  cakk-api/src/main/java/com/cakk/api/service/like/HeartService.java
  cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/jpa/CakeHeartJpaRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/jpa/CakeShopHeartJpaRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeHeartReader.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeShopHeartReader.java
Labels: feature

#109 Feature: batch 서버 구성 및 redis clear 관련 job 구현
  .github/workflows/weekly-batch-job.yml
  cakk-batch/build.gradle
  cakk-batch/src/main/java/com/cakk/batch/BatchApplication.java
  cakk-batch/src/main/java/com/cakk/batch/config/ComponentScanConfig.java
  cakk-batch/src/main/java/com/cakk/batch/config/SlackWebhookConfig.java
  cakk-batch/src/main/java/com/cakk/batch/job/config/ClearKeywordListJobConfig.java
  cakk-batch/src/main/java/com/cakk/batch/job/config/ClearViewsCakeIdListJobConfig.java
  cakk-batch/src/main/java/com/cakk/batch/job/launcher/WeeklyJobLauncher.java
  cakk-batch/src/main/java/com/cakk/batch/job/listener/JobLoggingListener.java
  cakk-batch/src/main/java/com/cakk/batch/service/SlackService.java
  cakk-batch/src/main/java/com/cakk/batch/tasklet/ClearKeywordListTasklet.java
  cakk-batch/src/main/java/com/cakk/batch/tasklet/ClearViewsCakeIdListTasklet.java
  cakk-batch/src/main/java/com/cakk/batch/tasklet/FindKeywordListTaskLet.java
  cakk-batch/src/main/java/com/cakk/batch/tasklet/FindViewsCakeIdListTaskLet.java
  cakk-batch/src/main/java/com/cakk/batch/utils/BatchConstants.java
  cakk-batch/src/main/java/com/cakk/batch/utils/BatchUtils.java
  cakk-batch/src/main/resources/application-local.yml
  cakk-batch/src/main/resources/application.yml
  cakk-batch/src/main/resources/batch-banner.dat
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/CakeViewRedisRepository.java
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/KeywordRedisRepository.java
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/template/RedisZSetTemplate.java
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/template/impl/RedisLongZSetTemplate.java
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/template/impl/RedisStringZSetTemplate.java
  settings.gradle
Labels: chore, feature

#114 Fix: 검색 시 위치 기반 미동의 시 조건부 로직으로 수정
  cakk-api/src/main/java/com/cakk/api/dto/request/cake/CakeSearchByLocationRequest.java
  cakk-api/src/main/java/com/cakk/api/dto/request/shop/CakeShopSearchRequest.java
  cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeQueryRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeShopQueryRepository.java
Labels: fix

#115 Feature: 케이크샵 사업자 연동 여부 조회
  cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
  cakk-api/src/main/java/com/cakk/api/dto/response/shop/CakeShopOwnerResponse.java
  cakk-api/src/main/java/com/cakk/api/mapper/ShopMapper.java
  cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
  cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/jpa/BusinessInformationJpaRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/BusinessInformationReader.java
Labels: feature

#117 Hotfix: 사진 확장자 변경
  cakk-external/src/main/java/com/cakk/external/service/S3Service.java
Labels: hotfix

#119 Hotfix: 백오피스 API에서 사업자인증번호 Validation 제거
  cakk-api/src/main/java/com/cakk/api/dto/request/shop/CreateShopRequest.java
Labels: hotfix

#122 Refactor: 케이크샵 생성 응답 필드 추가 및 케이크샵 정보 수정 필드 추가
  cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
  cakk-api/src/main/java/com/cakk/api/dto/request/shop/CreateShopRequest.java
  cakk-api/src/main/java/com/cakk/api/dto/request/shop/OperationDays.java
  cakk-api/src/main/java/com/cakk/api/dto/request/shop/UpdateShopRequest.java
  cakk-api/src/main/java/com/cakk/api/dto/response/shop/CakeShopCreateResponse.java
  cakk-api/src/main/java/com/cakk/api/mapper/ShopMapper.java
  cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
  cakk-api/src/main/java/com/cakk/api/validator/OperationValidator.java
  cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/service/shop/ShopServiceTest.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/shop/CakeShopUpdateParam.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/shop/CakeShop.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/writer/CakeShopWriter.java
Labels: refactor

#126 Refactor: 케이크샵 등록 시, 외부 링크 추가
  cakk-api/src/main/java/com/cakk/api/controller/advice/GlobalControllerAdvice.java
  cakk-api/src/main/java/com/cakk/api/dto/request/link/ShopLinkParam.java
  cakk-api/src/main/java/com/cakk/api/dto/request/shop/CreateShopRequest.java
  cakk-api/src/main/java/com/cakk/api/mapper/LinkMapper.java
  cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
  cakk-api/src/main/java/com/cakk/api/validator/OperationValidator.java
  cakk-api/src/test/java/com/cakk/api/service/shop/ShopServiceTest.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/writer/CakeShopWriter.java
Labels: refactor

#127 Feature: 이메일 인증 기능 구현
  cakk-api/src/main/java/com/cakk/api/controller/user/SignController.java
  cakk-api/src/main/java/com/cakk/api/dto/event/EmailWithVerificationCodeSendEvent.java
  cakk-api/src/main/java/com/cakk/api/dto/request/user/GenerateCodeRequest.java
  cakk-api/src/main/java/com/cakk/api/dto/request/user/VerifyEmailRequest.java
  cakk-api/src/main/java/com/cakk/api/listener/user/EmailSendEventListener.java
  cakk-api/src/main/java/com/cakk/api/mapper/EventMapper.java
  cakk-api/src/main/java/com/cakk/api/service/user/EmailVerificationService.java
  cakk-api/src/main/resources/application-local.yml
  cakk-api/src/test/resources/application-test.yml
  cakk-common/src/main/java/com/cakk/common/enums/RedisKey.java
  cakk-common/src/main/java/com/cakk/common/enums/ReturnCode.java
  cakk-common/src/main/java/com/cakk/common/utils/RandomUtils.java
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/EmailVerificationRedisRepository.java
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/TokenRedisRepository.java
  cakk-external/build.gradle
  cakk-external/src/main/java/com/cakk/external/config/MailConfig.java
  cakk-external/src/main/java/com/cakk/external/service/MailService.java
Labels: feature

#130 Refactor: mail 전송 관련 에러 로그 추가
  cakk-external/src/main/java/com/cakk/external/service/MailService.java
Labels: refactor

#135 Feature: 나의 케이크샵 아이디 조회
  cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
  cakk-api/src/main/java/com/cakk/api/dto/response/shop/CakeShopByMineResponse.java
  cakk-api/src/main/java/com/cakk/api/mapper/ShopMapper.java
  cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
  cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/jpa/BusinessInformationJpaRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/BusinessInformationReader.java
Labels: feature

#137 Hotfix: USER 권한에 따른 API 사용 권한 부여
  cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
  cakk-api/src/test/java/com/cakk/api/common/base/IntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
  cakk-api/src/test/resources/sql/insert-test-user.sql
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeQueryRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeShopQueryRepository.java
Labels: hotfix

#138 Hotfix: 케이크샵 조회 시, 권한에 따른 조건 수정
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeShopQueryRepository.java
Labels: hotfix

#139 Hotfix: 케이크 생성 시 사용 쿼리 수정
  cakk-api/src/main/java/com/cakk/api/config/SecurityConfig.java
  cakk-api/src/main/java/com/cakk/api/dto/request/cake/CakeUpdateRequest.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/jpa/CakeShopJpaRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeShopReader.java
Labels: hotfix
