Repository CAKK-DEV/cakk-server, pull requests merged in 2024-05, with the labels that each got.

#6 Feature: Entity 생성 및 Domain Service 어노테이션 작성
  .editorconfig
  build.gradle
  cakk-api/build.gradle
  cakk-api/src/main/java/com/cakk/api/Application.java
  cakk-common/src/main/java/com/cakk/common/enums/CakeDesignCategory.java
  cakk-common/src/main/java/com/cakk/common/enums/Gender.java
  cakk-common/src/main/java/com/cakk/common/enums/LinkKind.java
  cakk-common/src/main/java/com/cakk/common/enums/Provider.java
  cakk-common/src/main/java/com/cakk/common/enums/Role.java
  cakk-common/src/main/java/com/cakk/common/exception/CakkException.java
  cakk-domain/build.gradle
  cakk-domain/src/main/java/com/cakk/domain/annotation/Reader.java
  cakk-domain/src/main/java/com/cakk/domain/annotation/Writer.java
  cakk-domain/src/main/java/com/cakk/domain/config/DataSourceConfig.java
  cakk-domain/src/main/java/com/cakk/domain/config/P6spyConfig.java
  cakk-domain/src/main/java/com/cakk/domain/config/P6spySqlFormatterConfig.java
  cakk-domain/src/main/java/com/cakk/domain/config/QuerydslConfig.java
  cakk-domain/src/main/java/com/cakk/domain/entity/audit/AuditCreatedEntity.java
  cakk-domain/src/main/java/com/cakk/domain/entity/audit/AuditEntity.java
  cakk-domain/src/main/java/com/cakk/domain/entity/cake/Cake.java
  cakk-domain/src/main/java/com/cakk/domain/entity/cake/CakeCategory.java
  cakk-domain/src/main/java/com/cakk/domain/entity/cake/CakeLike.java
  cakk-domain/src/main/java/com/cakk/domain/entity/cake/CakeTag.java
  cakk-domain/src/main/java/com/cakk/domain/entity/cake/Tag.java
  cakk-domain/src/main/java/com/cakk/domain/entity/shop/CakeShop.java
  cakk-domain/src/main/java/com/cakk/domain/entity/shop/CakeShopLike.java
  cakk-domain/src/main/java/com/cakk/domain/entity/shop/CakeShopLink.java
  cakk-domain/src/main/java/com/cakk/domain/entity/user/BusinessInformation.java
  cakk-domain/src/main/java/com/cakk/domain/entity/user/User.java
  cakk-domain/src/main/resources/db-local.yml
  config/checkstyle/checkstyle-rules.xml
  config/checkstyle/checkstyle-suppressions.xml
  config/formatter/naver-intellij-formatter.xml
  gradle.properties
Labels: chore, feature

#7 Feature: Client 모듈 설정 및 OAuth 관련 RestClient 구현
  cakk-api/build.gradle
  cakk-client/build.gradle
  cakk-client/src/main/java/com/cakk/client/config/RestClientConfig.java
  cakk-client/src/main/java/com/cakk/client/vo/OidcPublicKey.java
  cakk-client/src/main/java/com/cakk/client/vo/OidcPublicKeyList.java
  cakk-client/src/main/java/com/cakk/client/web/AppleAuthClient.java
  cakk-client/src/main/java/com/cakk/client/web/GoogleAuthConfiguration.java
  cakk-client/src/main/java/com/cakk/client/web/KakaoAuthClient.java
  cakk-client/src/main/resources/client-local.yml
  cakk-common/src/main/java/com/cakk/common/enums/ReturnCode.java
  cakk-domain/build.gradle
  cakk-domain/src/main/java/com/cakk/domain/entity/user/User.java
  settings.gradle
Labels: chore, feature

#8 Feature: OidcProvider 구현 및 Spring Security 초기 설정
  .github/workflows/ci.yml
  README.md
  cakk-api/build.gradle
  cakk-api/src/main/java/com/cakk/api/common/response/ApiResponse.java
  cakk-api/src/main/java/com/cakk/api/config/ComponentScanConfig.java
  cakk-api/src/main/java/com/cakk/api/config/GoogleConfig.java
  cakk-api/src/main/java/com/cakk/api/config/JwtConfig.java
  cakk-api/src/main/java/com/cakk/api/config/SecurityConfig.java
  cakk-api/src/main/java/com/cakk/api/provider/jwt/JwtProvider.java
  cakk-api/src/main/java/com/cakk/api/provider/oauth/OidcProvider.java
  cakk-api/src/main/java/com/cakk/api/provider/oauth/PublicKeyProvider.java
  cakk-api/src/main/java/com/cakk/api/provider/oauth/impl/AppleAuthProvider.java
  cakk-api/src/main/java/com/cakk/api/provider/oauth/impl/GoogleAuthProvider.java
  cakk-api/src/main/java/com/cakk/api/provider/oauth/impl/KakaoAuthProvider.java
  cakk-api/src/main/java/com/cakk/api/vo/JsonWebToken.java
  cakk-api/src/main/java/com/cakk/api/vo/OAuthUserDetails.java
  cakk-api/src/main/resources/app-banner.dat
  cakk-api/src/main/resources/application-local.yml
  cakk-api/src/main/resources/application.yml
  cakk-api/src/test/java/com/cakk/api/ArchitectureTest.java
  cakk-api/src/test/java/com/cakk/api/common/base/ProviderTest.java
  cakk-api/src/test/java/com/cakk/api/common/utils/TestUtils.java
  cakk-api/src/test/java/com/cakk/api/provider/JwtProviderTest.java
  cakk-api/src/test/resources/application-test.yml
  cakk-client/build.gradle
  cakk-common/src/main/java/com/cakk/common/enums/ReturnCode.java
  cakk-common/src/main/java/com/cakk/common/enums/Role.java
  cakk-common/src/main/java/com/cakk/common/response/ApiResponse.java
  cakk-common/src/main/java/com/cakk/common/utils/DecodeUtils.java
  cakk-domain/src/main/resources/db-local.yml
  config/checkstyle/checkstyle-rules.xml
Labels: chore, feature

#9 Feature: Slack 웹훅 관련 기능 및 에러 핸들러 구현
  .github/workflows/ci.yml
  cakk-api/src/main/java/com/cakk/api/config/GoogleConfig.java
  cakk-api/src/main/java/com/cakk/api/config/JwtConfig.java
  cakk-api/src/main/java/com/cakk/api/config/SlackWebhookConfig.java
  cakk-api/src/main/java/com/cakk/api/controller/advice/GlobalControllerAdvice.java
  cakk-api/src/main/java/com/cakk/api/provider/jwt/JwtProvider.java
  cakk-api/src/main/java/com/cakk/api/service/slack/SlackService.java
  cakk-api/src/test/java/com/cakk/api/common/base/ProviderTest.java
  cakk-client/src/main/java/com/cakk/client/web/AppleAuthClient.java
  cakk-client/src/main/java/com/cakk/client/web/KakaoAuthClient.java
  cakk-client/src/main/resources/client-local.yml
  cakk-common/src/main/java/com/cakk/common/enums/ReturnCode.java
  cakk-common/src/main/java/com/cakk/common/exception/CakkException.java
  cakk-common/src/main/java/com/cakk/common/response/ApiResponse.java
Labels: feature

#11 Feature: External Module 추가 및 이미지 업로드 및 삭제 로직 추가
  cakk-api/build.gradle
  cakk-api/src/main/java/com/cakk/api/controller/s3/AwsS3Controller.java
  cakk-external/build.gradle
  cakk-external/src/main/java/com/cakk/external/config/S3Config.java
  cakk-external/src/main/java/com/cakk/external/service/S3Service.java
  cakk-external/src/main/java/com/cakk/external/vo/PresignedUrl.java
  settings.gradle
Labels: chore, feature

#12 Feature: 사업자 전환 기능 구현
  cakk-api/build.gradle
  cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
  cakk-api/src/main/java/com/cakk/api/controller/user/UserController.java
  cakk-api/src/main/java/com/cakk/api/dto/request/shop/CreateShopRequest.java
  cakk-api/src/main/java/com/cakk/api/dto/request/shop/PromotionRequest.java
  cakk-api/src/main/java/com/cakk/api/dto/request/user/CertificationRequest.java
  cakk-api/src/main/java/com/cakk/api/event/shop/listener/CertificationEventListener.java
  cakk-api/src/main/java/com/cakk/api/mapper/ShopMapper.java
  cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
  cakk-api/src/main/java/com/cakk/api/service/user/UserService.java
  cakk-common/src/main/java/com/cakk/common/enums/ReturnCode.java
  cakk-domain/src/main/java/com/cakk/domain/dto/param/user/CertificationParam.java
  cakk-domain/src/main/java/com/cakk/domain/entity/shop/CakeShop.java
  cakk-domain/src/main/java/com/cakk/domain/entity/user/BusinessInformation.java
  cakk-domain/src/main/java/com/cakk/domain/event/EventMapper.java
  cakk-domain/src/main/java/com/cakk/domain/event/shop/CertificationEvent.java
  cakk-domain/src/main/java/com/cakk/domain/repository/jpa/BusinessInformationJpaRepository.java
  cakk-domain/src/main/java/com/cakk/domain/repository/jpa/CakeShopJpaRepository.java
  cakk-domain/src/main/java/com/cakk/domain/repository/jpa/UserJpaRepository.java
  cakk-domain/src/main/java/com/cakk/domain/repository/reader/CakeShopReader.java
  cakk-domain/src/main/java/com/cakk/domain/repository/reader/UserReader.java
  cakk-domain/src/main/java/com/cakk/domain/repository/writer/CakeShopWriter.java
Labels: feature

#15 Feature: 사장 인증 외부 서비스 연동 및 비즈니스 로직 변경
  cakk-api/src/main/java/com/cakk/api/config/AsyncConfig.java
  cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
  cakk-api/src/main/java/com/cakk/api/event/shop/listener/CertificationEventListener.java
  cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
  cakk-api/src/main/java/com/cakk/api/service/slack/SlackService.java
  cakk-common/src/main/java/com/cakk/common/response/ApiResponse.java
  cakk-domain/build.gradle
  cakk-domain/src/main/java/com/cakk/domain/entity/user/BusinessInformation.java
  cakk-domain/src/test/java/com/cakk/domain/entity/user/BusinessInformationTest.java
Labels: feature, refactor

#16 Feature: 회원가입 및 로그인 구현
  .gitignore
  cakk-api/src/main/java/com/cakk/api/controller/user/SignController.java
  cakk-api/src/main/java/com/cakk/api/dto/request/user/UserSignInRequest.java
  cakk-api/src/main/java/com/cakk/api/dto/request/user/UserSignUpRequest.java
  cakk-api/src/main/java/com/cakk/api/dto/response/user/JwtResponse.java
  cakk-api/src/main/java/com/cakk/api/mapper/UserMapper.java
  cakk-api/src/main/java/com/cakk/api/service/user/UserService.java
  cakk-api/src/main/resources/application-local.yml
  cakk-api/src/main/resources/application.yml
  cakk-api/src/test/java/com/cakk/api/common/base/IntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/common/base/ServiceTest.java
  cakk-api/src/test/java/com/cakk/api/common/container/MysqlTestContainer.java
  cakk-api/src/test/java/com/cakk/api/service/user/UserServiceTest.java
  cakk-api/src/test/resources/application-test.yml
  cakk-common/src/main/java/com/cakk/common/enums/ReturnCode.java
  cakk-domain/src/main/java/com/cakk/domain/entity/user/User.java
  cakk-domain/src/main/java/com/cakk/domain/repository/jpa/UserJpaRepository.java
  cakk-domain/src/main/java/com/cakk/domain/repository/reader/UserReader.java
  cakk-domain/src/main/java/com/cakk/domain/repository/writer/UserWriter.java
  cakk-external/src/main/java/com/cakk/external/service/S3Service.java
Labels: chore, feature

#18 Deploy: 인프라 관련 dockerfile 및 설정파일 작성
  infra/certbot/.gitkeep
  infra/mysql/Dockerfile
  infra/mysql/start.sh
  infra/nginx/conf.d/app-server.conf
  infra/nginx/conf.d/nginx.conf
Labels: deploy

#20 Deploy: cd 워크플로우 및 shell 스크립트 작성
  .github/workflows/prod-app-api-cd.yml
  appspec.yml
  cakk-api/src/main/java/com/cakk/api/config/SecurityConfig.java
  cakk-api/src/main/java/com/cakk/api/provider/oauth/impl/GoogleAuthProvider.java
  cakk-common/src/main/java/com/cakk/common/enums/ReturnCode.java
  cakk-domain/src/main/java/com/cakk/domain/repository/writer/UserWriter.java
  scripts/start.sh
  scripts/stop.sh
Labels: deploy

#25 Fix: 사업자 등록 관련 비즈니스 로직 수정
  .github/workflows/prod-app-api-cd.yml
  cakk-api/src/main/java/com/cakk/api/dto/request/shop/CreateShopRequest.java
  cakk-api/src/main/java/com/cakk/api/mapper/ShopMapper.java
  cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
  cakk-api/src/test/java/com/cakk/api/common/base/ProviderTest.java
  cakk-common/src/main/java/com/cakk/common/enums/Days.java
  cakk-domain/src/main/java/com/cakk/domain/converter/DayOfWeekConverter.java
  cakk-domain/src/main/java/com/cakk/domain/entity/cake/CakeShopOperation.java
  cakk-domain/src/main/java/com/cakk/domain/entity/user/BusinessInformation.java
  cakk-domain/src/main/java/com/cakk/domain/repository/jpa/CakeShopOperationJpaRepository.java
  cakk-domain/src/main/java/com/cakk/domain/repository/writer/CakeShopWriter.java
Labels: fix, refactor

#27 Fix: Entity 생성 시 Default Value 지정
  cakk-domain/src/main/java/com/cakk/domain/entity/shop/CakeShop.java
Labels: fix

#29 Fix: 조회 쿼리 수정 및 비즈니스 로직 중 권한 변경 빠진 부분 추가
  cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
  cakk-common/src/main/java/com/cakk/common/enums/Role.java
  cakk-domain/src/main/java/com/cakk/domain/entity/user/BusinessInformation.java
  cakk-domain/src/main/java/com/cakk/domain/entity/user/User.java
  cakk-domain/src/main/java/com/cakk/domain/repository/jpa/BusinessInformationJpaRepository.java
  cakk-domain/src/main/java/com/cakk/domain/repository/reader/CakeShopReader.java
Labels: fix

#31 Feature: 카테고리별 케이크 사진 조회 비즈니스 구현
  cakk-api/src/main/java/com/cakk/api/dto/request/cake/CakeSearchByCategoryRequest.java
  cakk-api/src/main/java/com/cakk/api/dto/response/cake/CakeImageListResponse.java
  cakk-api/src/main/java/com/cakk/api/service/cake/CakeService.java
  cakk-api/src/test/java/com/cakk/api/service/cake/CakeServiceTest.java
  cakk-common/src/main/java/com/cakk/common/enums/CakeDesignCategory.java
  cakk-domain/src/main/java/com/cakk/domain/dto/param/cake/CakeImageResponseParam.java
  cakk-domain/src/main/java/com/cakk/domain/entity/shop/CakeShop.java
  cakk-domain/src/main/java/com/cakk/domain/repository/query/CakeQueryRepository.java
  cakk-domain/src/main/java/com/cakk/domain/repository/reader/CakeReader.java
  infra/nginx/Dockerfile
Labels: feature

#32 Test: CakeShop도메인 테스트 코드 리팩토링
  cakk-domain/src/test/java/com/cakk/domain/base/DomainTest.java
  cakk-domain/src/test/java/com/cakk/domain/entity/user/BusinessInformationTest.java
Labels: refactor

#33 Feature: 카테고리별 케이크 이미지 조회 API 구현
  cakk-api/src/main/java/com/cakk/api/controller/cake/CakeController.java
  cakk-api/src/main/java/com/cakk/api/dto/request/cake/CakeSearchByCategoryRequest.java
  cakk-api/src/main/java/com/cakk/api/mapper/ShopMapper.java
  cakk-api/src/main/java/com/cakk/api/service/cake/CakeService.java
  cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
  cakk-api/src/test/java/com/cakk/api/common/base/IntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/config/MockCustomUser.java
  cakk-api/src/test/java/com/cakk/api/config/WithMockCustomUserSecurityContextFactory.java
  cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.java
  cakk-api/src/test/resources/sql/delete-all.sql
  cakk-api/src/test/resources/sql/insert-cake.sql
  cakk-api/src/test/resources/sql/insert-test-user.sql
  cakk-common/src/main/java/com/cakk/common/enums/ReturnCode.java
  cakk-domain/src/main/java/com/cakk/domain/entity/cake/Cake.java
  cakk-domain/src/main/java/com/cakk/domain/entity/shop/CakeShop.java
  cakk-domain/src/main/java/com/cakk/domain/entity/shop/CakeShopOperation.java
  cakk-domain/src/main/java/com/cakk/domain/repository/jpa/CakeCategoryJpaRepository.java
  cakk-domain/src/main/java/com/cakk/domain/repository/jpa/CakeJpaRepository.java
  cakk-domain/src/main/java/com/cakk/domain/repository/jpa/CakeShopOperationJpaRepository.java
  cakk-domain/src/main/java/com/cakk/domain/repository/query/CakeQueryRepository.java
  cakk-domain/src/main/java/com/cakk/domain/repository/reader/CakeCategoryReader.java
  cakk-domain/src/main/java/com/cakk/domain/repository/reader/CakeReader.java
  cakk-domain/src/main/java/com/cakk/domain/repository/writer/CakeShopWriter.java
Labels: chore, feature

#35 Refactor: TestWithDisplayName 어노테이션 구현 및 적용
  cakk-api/src/main/java/com/cakk/api/service/cake/CakeService.java
  cakk-api/src/test/java/com/cakk/api/ArchitectureTest.java
  cakk-api/src/test/java/com/cakk/api/common/annotation/MockCustomUser.java
  cakk-api/src/test/java/com/cakk/api/common/annotation/TestWithDisplayName.java
  cakk-api/src/test/java/com/cakk/api/common/config/WithMockCustomUserSecurityContextFactory.java
  cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/provider/JwtProviderTest.java
  cakk-api/src/test/java/com/cakk/api/service/cake/CakeServiceTest.java
  cakk-api/src/test/java/com/cakk/api/service/user/UserServiceTest.java
  cakk-domain/src/main/java/com/cakk/domain/repository/query/CakeQueryRepository.java
  cakk-domain/src/main/java/com/cakk/domain/repository/reader/CakeReader.java
Labels: refactor

#36 Feature: 케이크 샵 하단 탭 조회 비즈니스 구현
  cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
  cakk-api/src/test/java/com/cakk/api/service/shop/ShopServiceTest.java
  cakk-api/src/test/resources/sql/insert-cake.sql
  cakk-domain/src/main/java/com/cakk/domain/dto/param/shop/CakeShopSimpleResponse.java
  cakk-domain/src/main/java/com/cakk/domain/entity/cake/Cake.java
  cakk-domain/src/main/java/com/cakk/domain/repository/query/CakeShopQueryRepository.java
  cakk-domain/src/main/java/com/cakk/domain/repository/reader/CakeShopReader.java
Labels: feature

#37 Feature: 케이크 샵 간단조회 API 구현
  .github/workflows/ci.yml
  .github/workflows/prod-app-api-cd.yml
  cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
  cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
  cakk-api/src/test/resources/sql/insert-cake-shop.sql
Labels: feature

#38 Feature: 케이크 샵 상세조회 비즈니스 로직 구현
  cakk-api/src/main/java/com/cakk/api/dto/response/shop/CakeShopDetailResponse.java
  cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
  cakk-api/src/test/java/com/cakk/api/service/shop/ShopServiceTest.java
  cakk-domain/src/main/java/com/cakk/domain/dto/param/shop/CakeShopDetailParam.java
  cakk-domain/src/main/java/com/cakk/domain/dto/param/shop/CakeShopLinkParam.java
  cakk-domain/src/main/java/com/cakk/domain/repository/query/CakeShopQueryRepository.java
  cakk-domain/src/main/java/com/cakk/domain/repository/reader/CakeShopReader.java
Labels: feature

#39 Feature: 케이크 샵 상세조회 API 구현
  cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
  cakk-api/src/main/java/com/cakk/api/dto/response/shop/CakeShopDetailResponse.java
  cakk-api/src/main/java/com/cakk/api/dto/response/shop/CakeShopSimpleResponse.java
  cakk-api/src/main/java/com/cakk/api/mapper/ShopMapper.java
  cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
  cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/service/shop/ShopServiceTest.java
  cakk-api/src/test/resources/sql/insert-cake-shop.sql
  cakk-common/src/main/java/com/cakk/common/enums/LinkKind.java
  cakk-domain/src/main/java/com/cakk/domain/converter/LinkKindConverter.java
  cakk-domain/src/main/java/com/cakk/domain/dto/param/shop/CakeShopDetailParam.java
  cakk-domain/src/main/java/com/cakk/domain/dto/param/shop/CakeShopSimpleParam.java
  cakk-domain/src/main/java/com/cakk/domain/entity/shop/CakeShopLink.java
  cakk-domain/src/main/java/com/cakk/domain/entity/shop/CakeShopOperation.java
  cakk-domain/src/main/java/com/cakk/domain/repository/jpa/CakeShopLinkJpaRepository.java
  cakk-domain/src/main/java/com/cakk/domain/repository/jpa/CakeShopOperationJpaRepository.java
  cakk-domain/src/main/java/com/cakk/domain/repository/query/CakeShopQueryRepository.java
  cakk-domain/src/main/java/com/cakk/domain/repository/reader/CakeShopLinkReader.java
  cakk-domain/src/main/java/com/cakk/domain/repository/reader/CakeShopOperationReader.java
  cakk-domain/src/main/java/com/cakk/domain/repository/reader/CakeShopReader.java
Labels: feature

#43 Feature: 케이크 샵에 속한 케이크 다건 조회 구현
  cakk-api/src/main/java/com/cakk/api/controller/cake/CakeController.java
  cakk-api/src/main/java/com/cakk/api/dto/request/cake/CakeSearchByShopRequest.java
  cakk-api/src/main/java/com/cakk/api/mapper/CakeMapper.java
  cakk-api/src/main/java/com/cakk/api/service/cake/CakeService.java
  cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/service/cake/CakeServiceTest.java
  cakk-api/src/test/resources/sql/insert-cake.sql
  cakk-domain/src/main/java/com/cakk/domain/repository/query/CakeQueryRepository.java
  cakk-domain/src/main/java/com/cakk/domain/repository/reader/CakeReader.java
Labels: feature, test

#45 Test: Shop 도메인 유닛 테스트 및 통합 테스트 추가
  cakk-api/src/main/java/com/cakk/api/annotation/OperationDays.java
  cakk-api/src/main/java/com/cakk/api/annotation/validator/OperationValidator.java
  cakk-api/src/main/java/com/cakk/api/controller/advice/GlobalControllerAdvice.java
  cakk-api/src/main/java/com/cakk/api/dto/request/shop/CreateShopRequest.java
  cakk-api/src/main/java/com/cakk/api/dto/request/shop/OperationDayRequest.java
  cakk-api/src/main/java/com/cakk/api/mapper/ShopMapper.java
  cakk-api/src/main/java/com/cakk/api/provider/jwt/JwtProvider.java
  cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
  cakk-api/src/main/resources/application.yml
  cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/service/shop/ShopServiceTest.java
  cakk-api/src/test/resources/application-test.yml
  cakk-api/src/test/resources/sql/insert-cake-shop.sql
  cakk-api/src/test/resources/sql/insert-test-user.sql
  cakk-common/src/main/java/com/cakk/common/enums/ReturnCode.java
  cakk-domain/build.gradle
  cakk-domain/src/main/java/com/cakk/domain/config/JacksonConfig.java
  cakk-domain/src/main/java/com/cakk/domain/entity/audit/AuditEntity.java
  cakk-domain/src/main/java/com/cakk/domain/entity/user/User.java
Labels: chore, fix, test

#46 Feature: 케이크 샵 상세 정보 조회 구현
  cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
  cakk-api/src/main/java/com/cakk/api/dto/response/shop/CakeShopInfoResponse.java
  cakk-api/src/main/java/com/cakk/api/mapper/ShopMapper.java
  cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
  cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/service/shop/ShopServiceTest.java
  cakk-api/src/test/resources/sql/insert-cake-shop.sql
  cakk-domain/src/main/java/com/cakk/domain/dto/param/shop/CakeShopInfoParam.java
  cakk-domain/src/main/java/com/cakk/domain/dto/param/shop/CakeShopOperationParam.java
  cakk-domain/src/main/java/com/cakk/domain/entity/shop/CakeShop.java
  cakk-domain/src/main/java/com/cakk/domain/repository/query/CakeShopQueryRepository.java
  cakk-domain/src/main/java/com/cakk/domain/repository/reader/CakeShopReader.java
Labels: feature, test
