Repository CAKK-DEV/cakk-server, pull requests merged in 2024-09, with the labels that each got.

#203 Refactor | CAKK-57 | 케이크 도메인 로직 리팩토링
  cakk-api/src/main/java/com/cakk/api/service/cake/CakeService.java
  cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/annotation/DomainFacade.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/facade/cake/CakeManagerFacade.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/jpa/TagJpaRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/TagReader.java
Labels: refactor

#204 Refactor | CAKK-62 | external 모듈 kt 전환
  cakk-api/src/test/java/com/cakk/api/controller/AwsS3ControllerTest.java
  cakk-external/src/main/java/com/cakk/external/config/S3Config.java
  cakk-external/src/main/java/com/cakk/external/config/S3Config.kt
  cakk-external/src/main/java/com/cakk/external/service/S3Service.java
  cakk-external/src/main/java/com/cakk/external/service/S3Service.kt
  cakk-external/src/main/java/com/cakk/external/vo/CertificationMessage.java
  cakk-external/src/main/java/com/cakk/external/vo/CertificationMessage.kt
  cakk-external/src/main/java/com/cakk/external/vo/PresignedUrl.java
  cakk-external/src/main/java/com/cakk/external/vo/PresignedUrl.kt
Labels: refactor

#205 Refactor | CAKK-63 | Writer를 Facade로 변경
  cakk-admin/src/main/kotlin/com/cakk/admin/service/CakeService.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/service/ShopService.kt
  cakk-api/src/main/java/com/cakk/api/service/cake/CakeService.java
  cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
  cakk-api/src/main/java/com/cakk/api/service/user/SignService.java
  cakk-api/src/main/java/com/cakk/api/service/user/UserService.java
  cakk-api/src/test/java/com/cakk/api/service/shop/ShopServiceTest.java
  cakk-api/src/test/java/com/cakk/api/service/user/SignServiceTest.java
  cakk-api/src/test/java/com/cakk/api/service/user/UserServiceTest.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/annotation/Writer.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/shop/CakeShop.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/facade/cake/CakeManagerFacade.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/facade/shop/CakeShopManagerFacade.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/facade/tag/TagManagerFacade.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/facade/user/UserManagerFacade.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/TagReader.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/writer/CakeShopWriter.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/writer/CakeWriter.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/writer/TagWriter.java
  cakk-domain/mysql/src/test/java/com/cakk/domain/facade/user/UserManagerFacadeTest.java
Labels: refactor

#206 Refactor | CAKK-65 | 공통모듈 kt 전환
  build.gradle.kts
  cakk-api/src/main/java/com/cakk/api/mapper/ShopMapper.java
  cakk-api/src/main/java/com/cakk/api/provider/oauth/OidcProvider.java
  cakk-api/src/main/java/com/cakk/api/provider/oauth/PublicKeyProvider.java
  cakk-api/src/main/java/com/cakk/api/service/user/EmailVerificationService.java
  cakk-common/src/main/java/com/cakk/common/enums/CakeDesignCategory.java
  cakk-common/src/main/java/com/cakk/common/enums/CakeDesignCategory.kt
  cakk-common/src/main/java/com/cakk/common/enums/Days.java
  cakk-common/src/main/java/com/cakk/common/enums/Days.kt
  cakk-common/src/main/java/com/cakk/common/enums/Gender.java
  cakk-common/src/main/java/com/cakk/common/enums/Gender.kt
  cakk-common/src/main/java/com/cakk/common/enums/LinkKind.java
  cakk-common/src/main/java/com/cakk/common/enums/LinkKind.kt
  cakk-common/src/main/java/com/cakk/common/enums/Provider.java
  cakk-common/src/main/java/com/cakk/common/enums/Provider.kt
  cakk-common/src/main/java/com/cakk/common/enums/RedisKey.java
  cakk-common/src/main/java/com/cakk/common/enums/RedisKey.kt
  cakk-common/src/main/java/com/cakk/common/enums/ReturnCode.java
  cakk-common/src/main/java/com/cakk/common/enums/ReturnCode.kt
  cakk-common/src/main/java/com/cakk/common/enums/Role.java
  cakk-common/src/main/java/com/cakk/common/enums/Role.kt
  cakk-common/src/main/java/com/cakk/common/enums/VerificationStatus.java
  cakk-common/src/main/java/com/cakk/common/enums/VerificationStatus.kt
  cakk-common/src/main/java/com/cakk/common/exception/CakkException.java
  cakk-common/src/main/java/com/cakk/common/exception/CakkException.kt
  cakk-common/src/main/java/com/cakk/common/response/ApiResponse.java
  cakk-common/src/main/java/com/cakk/common/utils/DecodeUtils.java
  cakk-common/src/main/java/com/cakk/common/utils/DecodeUtils.kt
  cakk-common/src/main/java/com/cakk/common/utils/RandomUtils.java
  cakk-common/src/main/java/com/cakk/common/utils/RandomUtils.kt
  cakk-common/src/main/java/com/cakk/common/utils/SetUtils.java
  cakk-common/src/main/java/com/cakk/common/utils/SetUtils.kt
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/converter/DayOfWeekConverter.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/converter/VerificationStatusConverter.java
Labels: refactor

#209 Refactor | CAKK-81 | External 모듈, Client 모듈 통합
  cakk-api/build.gradle.kts
  cakk-api/src/main/java/com/cakk/api/controller/s3/AwsS3Controller.java
  cakk-api/src/main/java/com/cakk/api/listener/CertificationEventListener.java
  cakk-api/src/main/java/com/cakk/api/listener/EmailSendEventListener.java
  cakk-api/src/main/java/com/cakk/api/listener/ErrorAlertEventListener.java
  cakk-api/src/main/java/com/cakk/api/mapper/EventMapper.java
  cakk-api/src/main/java/com/cakk/api/provider/oauth/PublicKeyProvider.java
  cakk-api/src/main/java/com/cakk/api/provider/oauth/impl/AppleAuthProvider.java
  cakk-api/src/main/java/com/cakk/api/provider/oauth/impl/KakaoAuthProvider.java
  cakk-api/src/test/java/com/cakk/api/common/base/MockitoTest.java
  cakk-api/src/test/java/com/cakk/api/controller/AwsS3ControllerTest.java
  cakk-api/src/test/java/com/cakk/api/provider/AppleAuthProviderTest.java
  cakk-api/src/test/java/com/cakk/api/provider/KakaoAuthProviderTest.java
  cakk-client/build.gradle
  cakk-client/src/main/java/com/cakk/client/config/RestClientConfig.java
  cakk-client/src/main/java/com/cakk/client/vo/OidcPublicKey.java
  cakk-client/src/main/java/com/cakk/client/vo/OidcPublicKeyList.java
  cakk-client/src/main/java/com/cakk/client/web/AppleAuthClient.java
  cakk-client/src/main/java/com/cakk/client/web/KakaoAuthClient.java
  cakk-core/build.gradle.kts
  cakk-external/build.gradle.kts
  cakk-external/src/main/kotlin/com/cakk/external/client/AppleAuthClient.kt
  cakk-external/src/main/kotlin/com/cakk/external/client/KakaoAuthClient.kt
  cakk-external/src/main/kotlin/com/cakk/external/config/EmailConfig.kt
  cakk-external/src/main/kotlin/com/cakk/external/config/RestClientConfig.kt
  cakk-external/src/main/kotlin/com/cakk/external/config/S3Config.kt
  cakk-external/src/main/kotlin/com/cakk/external/config/SlackWebhookConfig.kt
  cakk-external/src/main/kotlin/com/cakk/external/extractor/CertificationSlackMessageExtractor.kt
  cakk-external/src/main/kotlin/com/cakk/external/extractor/ErrorAlertSlackMessageExtractor.kt
  cakk-external/src/main/kotlin/com/cakk/external/extractor/MessageExtractor.kt
  cakk-external/src/main/kotlin/com/cakk/external/extractor/MimeMessageExtractor.kt
  cakk-external/src/main/kotlin/com/cakk/external/extractor/SlackMessageExtractor.kt
  cakk-external/src/main/kotlin/com/cakk/external/extractor/VerificationCodeMimeMessageExtractor.kt
  cakk-external/src/main/kotlin/com/cakk/external/sender/EmailMessageSender.kt
  cakk-external/src/main/kotlin/com/cakk/external/sender/MessageSender.kt
  cakk-external/src/main/kotlin/com/cakk/external/sender/SlackMessageSender.kt
  cakk-external/src/main/kotlin/com/cakk/external/service/S3Service.kt
  cakk-external/src/main/kotlin/com/cakk/external/template/MessageTemplate.kt
  cakk-external/src/main/kotlin/com/cakk/external/vo/key/OidcPublicKey.kt
  cakk-external/src/main/kotlin/com/cakk/external/vo/key/OidcPublicKeyList.kt
  cakk-external/src/main/kotlin/com/cakk/external/vo/message/CertificationMessage.kt
  cakk-external/src/main/kotlin/com/cakk/external/vo/message/ErrorAlertMessage.kt
  cakk-external/src/main/kotlin/com/cakk/external/vo/message/VerificationMessage.kt
  cakk-external/src/main/kotlin/com/cakk/external/vo/s3/PresignedUrl.kt
  settings.gradle.kts
Labels: refactor

#211 Refactor | CAKK-83 | 통합테스트 kt 전환 및 kotest 도입
  cakk-api/build.gradle.kts
  cakk-api/src/main/java/com/cakk/api/annotation/ApplicationEventListener.java
  cakk-api/src/main/java/com/cakk/api/annotation/ApplicationEventListener.kt
  cakk-api/src/main/java/com/cakk/api/dto/event/EmailWithVerificationCodeSendEvent.java
  cakk-api/src/main/java/com/cakk/api/dto/event/EmailWithVerificationCodeSendEvent.kt
  cakk-api/src/main/java/com/cakk/api/dto/event/ErrorAlertEvent.java
  cakk-api/src/main/java/com/cakk/api/dto/event/ErrorAlertEvent.kt
  cakk-api/src/main/java/com/cakk/api/dto/event/IncreaseSearchCountEvent.java
  cakk-api/src/main/java/com/cakk/api/dto/event/IncreaseSearchCountEvent.kt
  cakk-api/src/main/java/com/cakk/api/listener/SearchEventListener.java
  cakk-api/src/main/java/com/cakk/api/listener/SearchEventListener.kt
  cakk-api/src/main/java/com/cakk/api/mapper/EventMapper.java
  cakk-api/src/main/java/com/cakk/api/service/cake/CakeService.java
  cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
  cakk-api/src/test/java/com/cakk/api/common/base/IntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/common/base/IntegrationTest.kt
  cakk-api/src/test/java/com/cakk/api/integration/admin/AdminIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/integration/admin/AdminIntegrationTest.kt
  cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.kt
  cakk-api/src/test/java/com/cakk/api/integration/search/KeywordIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/integration/search/KeywordIntegrationTest.kt
  cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.kt
  cakk-api/src/test/java/com/cakk/api/integration/user/HeartIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/integration/user/HeartIntegrationTest.kt
  cakk-api/src/test/java/com/cakk/api/integration/user/MyPageIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/integration/user/MyPageIntegrationTest.kt
  cakk-api/src/test/java/com/cakk/api/integration/user/SignIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/integration/user/SignIntegrationTest.kt
  cakk-api/src/test/java/com/cakk/api/listener/EmailSendEventListenerTest.java
  cakk-api/src/test/java/com/cakk/api/listener/SearchEventListenerTest.java
  cakk-core/src/test/kotlin/com/cakk/core/common/base/FacadeTest.kt
Labels: refactor, test

#213 Refactor | CAKK-85 | Controller kt 변환과 dto 리팩토링
  cakk-api/src/main/java/com/cakk/api/controller/s3/AwsS3Controller.java
  cakk-api/src/main/java/com/cakk/api/controller/s3/AwsS3Controller.kt
  cakk-api/src/main/java/com/cakk/api/controller/search/KeywordController.java
  cakk-api/src/main/java/com/cakk/api/controller/search/KeywordController.kt
  cakk-api/src/main/java/com/cakk/api/controller/shop/AdminController.java
  cakk-api/src/main/java/com/cakk/api/controller/shop/AdminController.kt
  cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
  cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.kt
  cakk-api/src/main/java/com/cakk/api/controller/user/MyPageController.java
  cakk-api/src/main/java/com/cakk/api/controller/user/MyPageController.kt
  cakk-api/src/main/java/com/cakk/api/controller/user/SignController.java
  cakk-api/src/main/java/com/cakk/api/controller/user/SignController.kt
  cakk-api/src/main/java/com/cakk/api/dto/param/link/ShopLinkParam.java
  cakk-api/src/main/java/com/cakk/api/dto/param/operation/ShopOperationParam.java
  cakk-api/src/main/java/com/cakk/api/dto/request/link/UpdateLinkRequest.java
  cakk-api/src/main/java/com/cakk/api/dto/request/operation/UpdateShopOperationRequest.java
  cakk-api/src/main/java/com/cakk/api/dto/request/shop/CakeShopSearchRequest.java
  cakk-api/src/main/java/com/cakk/api/dto/request/shop/CreateShopRequest.java
  cakk-api/src/main/java/com/cakk/api/dto/request/shop/UpdateShopRequest.java
  cakk-api/src/main/java/com/cakk/api/dto/request/user/CertificationRequest.java
  cakk-api/src/main/java/com/cakk/api/mapper/LinkMapper.java
  cakk-api/src/main/java/com/cakk/api/mapper/SearchMapper.java
  cakk-api/src/main/java/com/cakk/api/mapper/ShopMapper.java
  cakk-api/src/main/java/com/cakk/api/mapper/ShopOperationMapper.java
  cakk-api/src/main/java/com/cakk/api/mapper/UserMapper.java
  cakk-api/src/main/java/com/cakk/api/service/like/HeartService.java
  cakk-api/src/main/java/com/cakk/api/service/search/KeywordService.java
  cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
  cakk-api/src/main/java/com/cakk/api/service/user/SignService.java
  cakk-api/src/main/java/com/cakk/api/service/user/UserService.java
  cakk-api/src/main/java/com/cakk/api/validator/OperationValidator.java
  cakk-api/src/test/java/com/cakk/api/controller/SignControllerTest.java
  cakk-api/src/test/java/com/cakk/api/integration/admin/AdminIntegrationTest.kt
  cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.kt
  cakk-api/src/test/java/com/cakk/api/service/like/HeartServiceTest.java
  cakk-api/src/test/java/com/cakk/api/service/search/KeywordServiceTest.java
  cakk-api/src/test/java/com/cakk/api/service/shop/ShopServiceTest.java
  cakk-api/src/test/java/com/cakk/api/service/user/SignServiceTest.java
  cakk-api/src/test/java/com/cakk/api/service/user/UserServiceTest.java
  cakk-api/src/test/java/com/cakk/api/validator/OperationValidatorTest.java
  cakk-core/src/main/kotlin/com/cakk/core/dto/param/search/CakeShopSearchByViewsParam.kt
  cakk-core/src/main/kotlin/com/cakk/core/dto/param/search/HeartCakeSearchParam.kt
  cakk-core/src/main/kotlin/com/cakk/core/dto/param/search/HeartCakeShopSearchParam.kt
  cakk-core/src/main/kotlin/com/cakk/core/dto/param/search/SearchShopByLocationParam.kt
  cakk-core/src/main/kotlin/com/cakk/core/dto/param/search/TopSearchedListParam.kt
  cakk-core/src/main/kotlin/com/cakk/core/dto/param/shop/CreateShopParam.kt
  cakk-core/src/main/kotlin/com/cakk/core/dto/param/shop/PromotionParam.kt
  cakk-core/src/main/kotlin/com/cakk/core/dto/param/shop/ShopLinkParam.kt
  cakk-core/src/main/kotlin/com/cakk/core/dto/param/shop/ShopOperationParam.kt
  cakk-core/src/main/kotlin/com/cakk/core/dto/param/user/UserSignInParam.kt
  cakk-core/src/main/kotlin/com/cakk/core/dto/param/user/UserSignUpParam.kt
  cakk-core/src/test/kotlin/com/cakk/core/common/base/FacadeTest.kt
  cakk-core/src/test/kotlin/com/cakk/core/facade/UserManageFacadeTest.kt
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/user/ProfileUpdateParam.java
Labels: refactor

#214 Refactor | CAKK-86 | 일부 파일 코틀린 전환
  cakk-api/src/main/java/com/cakk/api/controller/cake/CakeController.kt
  cakk-api/src/main/java/com/cakk/api/controller/search/KeywordController.kt
  cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.kt
  cakk-api/src/main/java/com/cakk/api/controller/user/MyPageController.kt
  cakk-api/src/main/java/com/cakk/api/controller/user/SignController.kt
  cakk-api/src/main/java/com/cakk/api/dto/response/like/HeartCakeImageListResponse.java
  cakk-api/src/main/java/com/cakk/api/dto/response/like/HeartCakeShopListResponse.java
  cakk-api/src/main/java/com/cakk/api/dto/response/like/HeartResponse.java
  cakk-api/src/main/java/com/cakk/api/dto/response/search/TopSearchedListResponse.java
  cakk-api/src/main/java/com/cakk/api/dto/response/user/JwtResponse.java
  cakk-api/src/main/java/com/cakk/api/dto/response/user/ProfileInformationResponse.java
  cakk-api/src/main/java/com/cakk/api/mapper/CakeMapper.java
  cakk-api/src/main/java/com/cakk/api/mapper/EventMapper.java
  cakk-api/src/main/java/com/cakk/api/mapper/HeartMapper.java
  cakk-api/src/main/java/com/cakk/api/mapper/SearchMapper.java
  cakk-api/src/main/java/com/cakk/api/mapper/ShopMapper.java
  cakk-api/src/main/java/com/cakk/api/mapper/UserMapper.java
  cakk-api/src/main/java/com/cakk/api/mapper/UserMapper.kt
  cakk-api/src/main/java/com/cakk/api/provider/jwt/JwtProvider.java
  cakk-api/src/main/java/com/cakk/api/provider/jwt/JwtProvider.kt
  cakk-api/src/main/java/com/cakk/api/service/like/HeartService.java
  cakk-api/src/main/java/com/cakk/api/service/search/KeywordService.java
  cakk-api/src/main/java/com/cakk/api/service/user/SignService.java
  cakk-api/src/main/java/com/cakk/api/service/user/UserService.java
  cakk-api/src/main/java/com/cakk/api/vo/JsonWebToken.java
  cakk-api/src/main/java/com/cakk/api/vo/JsonWebToken.kt
  cakk-api/src/test/java/com/cakk/api/common/base/IntegrationTest.kt
  cakk-api/src/test/java/com/cakk/api/controller/SignControllerTest.java
  cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.kt
  cakk-api/src/test/java/com/cakk/api/integration/search/KeywordIntegrationTest.kt
  cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.kt
  cakk-api/src/test/java/com/cakk/api/integration/user/HeartIntegrationTest.kt
  cakk-api/src/test/java/com/cakk/api/integration/user/MyPageIntegrationTest.kt
  cakk-api/src/test/java/com/cakk/api/integration/user/SignIntegrationTest.kt
  cakk-api/src/test/java/com/cakk/api/provider/JwtProviderTest.java
  cakk-api/src/test/java/com/cakk/api/service/like/HeartServiceTest.java
  cakk-api/src/test/java/com/cakk/api/service/search/KeywordServiceTest.java
  cakk-api/src/test/java/com/cakk/api/service/user/SignServiceTest.java
  cakk-api/src/test/java/com/cakk/api/service/user/UserServiceTest.java
  cakk-core/src/main/kotlin/com/cakk/core/dto/response/like/HeartCakeImageListResponse.kt
  cakk-core/src/main/kotlin/com/cakk/core/dto/response/like/HeartCakeShopListResponse.kt
  cakk-core/src/main/kotlin/com/cakk/core/dto/response/like/HeartResponse.kt
  cakk-core/src/main/kotlin/com/cakk/core/dto/response/search/TopSearchedListResponse.kt
  cakk-core/src/main/kotlin/com/cakk/core/dto/response/user/JwtResponse.kt
  cakk-core/src/main/kotlin/com/cakk/core/dto/response/user/ProfileInformationResponse.kt
  cakk-core/src/main/kotlin/com/cakk/core/mapper/HeartMapper.kt
Labels: refactor

#218 Hotfix | CAKK-89 | objectmapper 설정 수정
  cakk-api/src/main/kotlin/com/cakk/api/config/JacksonConfig.kt
  cakk-core/src/main/kotlin/com/cakk/core/service/user/SignService.kt
Labels: hotfix
