Repository CAKK-DEV/cakk-server, pull requests merged in 2024-10, with the labels that each got.

#219 Refactor | CAKK-91 | 의존성 관련 리팩토링
  cakk-api/src/test/java/com/cakk/api/controller/SignControllerTest.kt
  cakk-core/src/main/kotlin/com/cakk/core/facade/cake/CakeReadFacade.kt
  cakk-core/src/main/kotlin/com/cakk/core/facade/cake/CakeShopReadFacade.kt
  cakk-core/src/main/kotlin/com/cakk/core/service/cake/CakeService.kt
  cakk-core/src/main/kotlin/com/cakk/core/service/shop/ShopService.kt
  cakk-core/src/test/kotlin/com/cakk/core/service/cake/CakeServiceTest.kt
  cakk-core/src/test/kotlin/com/cakk/core/service/shop/ShopServiceTest.kt
Labels: refactor

#220 Refactor | CAKK-92 | 어드민 서버 코드 리팩토링
  cakk-admin/build.gradle.kts
  cakk-admin/src/main/kotlin/com/cakk/admin/annotation/AdminUser.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/annotation/OperationDay.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/controller/BusinessInformationController.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/controller/CakeController.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/controller/ShopController.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/param/CakeCreateByAdminParam.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/param/CakeShopCreateByAdminParam.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/param/CakeUpdateByAdminParam.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/param/OwnerCandidateParam.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/param/ShopLinkParam.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/request/AddressUpdateByAdminRequest.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/request/CakeCreateByAdminRequest.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/request/CakeShopCreateByAdminRequest.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/request/CakeShopUpdateByAdminRequest.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/request/CakeUpdateByAdminRequest.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/request/LinkUpdateByAdminRequest.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/request/PromotionRequest.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/request/ShopOperationUpdateByAdminRequest.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/response/CakeShopCreateResponse.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/response/CakeShopOwnerCandidateResponse.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/response/CakeShopOwnerCandidatesResponse.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/response/TagResponse.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/mapper/BusinessInformationMapper.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/mapper/CakeDesignCategoryMapper.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/mapper/CakeMapper.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/mapper/LinkMapper.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/mapper/PointMapper.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/mapper/ShopMapper.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/mapper/ShopOperationMapper.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/resolver/AdminUserResolver.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/service/BusinessInformationService.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/service/CakeService.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/service/ShopService.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/validator/OperationValidator.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/vo/OAuthUserDetails.kt
  cakk-api/src/main/kotlin/com/cakk/api/mapper/ShopMapper.kt
  cakk-domain/mysql/src/test/java/com/cakk/domain/entity/user/BusinessInformationTest.kt
Labels: chore, refactor

#222 Refactor | CAKK-94 | 케이크 이미지 조회에 대한 로직 리팩토링
  cakk-api/src/main/kotlin/com/cakk/api/controller/cake/CakeController.kt
  cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.kt
  cakk-core/src/main/kotlin/com/cakk/core/dto/response/cake/CakeImageListResponse.kt
  cakk-core/src/main/kotlin/com/cakk/core/dto/response/cake/CakeImageWithShopInfoListResponse.kt
  cakk-core/src/main/kotlin/com/cakk/core/facade/cake/CakeReadFacade.kt
  cakk-core/src/main/kotlin/com/cakk/core/mapper/CakeMapper.kt
  cakk-core/src/main/kotlin/com/cakk/core/service/cake/CakeService.kt
  cakk-core/src/test/kotlin/com/cakk/core/service/cake/CakeServiceTest.kt
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/cake/CakeImageResponseParam.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/cake/CakeImageWithShopInfoResponseParam.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeQueryRepository.java
Labels: refactor

#223 Deploy | CAKK-94 | v2.0.6 배포
  cakk-admin/build.gradle.kts
  cakk-admin/src/main/kotlin/com/cakk/admin/annotation/AdminUser.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/annotation/OperationDay.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/controller/BusinessInformationController.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/controller/CakeController.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/controller/ShopController.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/param/CakeCreateByAdminParam.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/param/CakeShopCreateByAdminParam.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/param/CakeUpdateByAdminParam.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/param/OwnerCandidateParam.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/param/ShopLinkParam.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/request/AddressUpdateByAdminRequest.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/request/CakeCreateByAdminRequest.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/request/CakeShopCreateByAdminRequest.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/request/CakeShopUpdateByAdminRequest.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/request/CakeUpdateByAdminRequest.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/request/LinkUpdateByAdminRequest.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/request/PromotionRequest.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/request/ShopOperationUpdateByAdminRequest.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/response/CakeShopCreateResponse.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/response/CakeShopOwnerCandidateResponse.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/response/CakeShopOwnerCandidatesResponse.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/response/TagResponse.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/mapper/BusinessInformationMapper.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/mapper/CakeDesignCategoryMapper.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/mapper/CakeMapper.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/mapper/LinkMapper.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/mapper/PointMapper.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/mapper/ShopMapper.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/mapper/ShopOperationMapper.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/resolver/AdminUserResolver.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/service/BusinessInformationService.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/service/CakeService.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/service/ShopService.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/validator/OperationValidator.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/vo/OAuthUserDetails.kt
  cakk-api/src/main/kotlin/com/cakk/api/controller/cake/CakeController.kt
  cakk-api/src/main/kotlin/com/cakk/api/mapper/ShopMapper.kt
  cakk-api/src/test/java/com/cakk/api/controller/SignControllerTest.kt
  cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.kt
  cakk-core/src/main/kotlin/com/cakk/core/dto/response/cake/CakeImageListResponse.kt
  cakk-core/src/main/kotlin/com/cakk/core/dto/response/cake/CakeImageWithShopInfoListResponse.kt
  cakk-core/src/main/kotlin/com/cakk/core/facade/cake/CakeReadFacade.kt
  cakk-core/src/main/kotlin/com/cakk/core/facade/cake/CakeShopReadFacade.kt
  cakk-core/src/main/kotlin/com/cakk/core/mapper/CakeMapper.kt
  cakk-core/src/main/kotlin/com/cakk/core/service/cake/CakeService.kt
  cakk-core/src/main/kotlin/com/cakk/core/service/shop/ShopService.kt
  cakk-core/src/test/kotlin/com/cakk/core/service/cake/CakeServiceTest.kt
  cakk-core/src/test/kotlin/com/cakk/core/service/shop/ShopServiceTest.kt
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/cake/CakeImageResponseParam.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/cake/CakeImageWithShopInfoResponseParam.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeQueryRepository.java
  cakk-domain/mysql/src/test/java/com/cakk/domain/entity/user/BusinessInformationTest.kt
Labels: deploy
