Repository CAKK-DEV/cakk-server, pull requests merged in 2024-07, with the labels that each got.

#140 Refactor: 조회수 레포지토리 네이밍 수정
  cakk-api/src/main/java/com/cakk/api/listener/views/ViewsIncreaseEventListener.java
  cakk-api/src/main/java/com/cakk/api/service/cake/CakeService.java
  cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/service/cake/CakeServiceTest.java
  cakk-batch/src/main/java/com/cakk/batch/tasklet/ClearViewsCakeIdListTasklet.java
  cakk-batch/src/main/java/com/cakk/batch/tasklet/FindViewsCakeIdListTaskLet.java
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/CakeViewsRedisRepository.java
Labels: refactor

#141 Hotfix: 케이크 상세 조회 쿼리 오류 수정
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeQueryRepository.java
Labels: hotfix

#142 Hotfix: 케이크 카테고리 및 태그 존재 유무에 따른 테스트 및 response 수정
  cakk-api/src/main/java/com/cakk/api/mapper/CakeMapper.java
  cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.java
  cakk-api/src/test/resources/sql/insert-cake.sql
Labels: hotfix

#143 Feature: 케이크 샵 조회수 상승 로직 구현
  cakk-api/src/main/java/com/cakk/api/listener/views/ViewsIncreaseEventListener.java
  cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
  cakk-api/src/main/java/com/cakk/api/service/slack/SlackService.java
  cakk-common/src/main/java/com/cakk/common/enums/RedisKey.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/event/EventMapper.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/event/views/CakeShopIncreaseViewsEvent.java
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/CakeShopViewsRedisRepository.java
Labels: feature

#146 Hotfix: 케이크 검색, 상세 조회 쿼리 수정
  cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeQueryRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeShopQueryRepository.java
Labels: hotfix

#145 Feature: 인기 케이크 샵 조회 구현
  cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
  cakk-api/src/main/java/com/cakk/api/dto/request/shop/CakeShopSearchByViewsRequest.java
  cakk-api/src/main/java/com/cakk/api/mapper/ShopMapper.java
  cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
  cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/service/shop/ShopServiceTest.java
  cakk-api/src/test/resources/application-test.yml
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/bo/CakeShops.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/shop/CakeShopParam.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeShopQueryRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeShopReader.java
Labels: feature

#148 Hotfix: 위치 기반 검색 쿼리 오류 및 케이크 샵 정보 조회 쿼리 수정
  cakk-api/src/main/java/com/cakk/api/mapper/CakeMapper.java
  cakk-api/src/main/java/com/cakk/api/mapper/ShopMapper.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/bo/CakeShops.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/shop/CakeShopParam.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeShopQueryRepository.java
Labels: hotfix

#150 Refactor: 네이밍 및 코드 컨벤션을 위한 리팩토링
  cakk-api/src/main/java/com/cakk/api/annotation/ApplicationEventListener.java
  cakk-api/src/main/java/com/cakk/api/controller/advice/GlobalControllerAdvice.java
  cakk-api/src/main/java/com/cakk/api/controller/cake/CakeController.java
  cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
  cakk-api/src/main/java/com/cakk/api/controller/user/MyPageController.java
  cakk-api/src/main/java/com/cakk/api/factory/OidcProviderFactory.java
  cakk-api/src/main/java/com/cakk/api/listener/shop/CertificationEventListener.java
  cakk-api/src/main/java/com/cakk/api/listener/user/EmailSendEventListener.java
  cakk-api/src/main/java/com/cakk/api/listener/views/ViewsIncreaseEventListener.java
  cakk-api/src/main/java/com/cakk/api/mapper/CakeDesignCategoryMapper.java
  cakk-api/src/main/java/com/cakk/api/mapper/CakeMapper.java
  cakk-api/src/main/java/com/cakk/api/mapper/EventMapper.java
  cakk-api/src/main/java/com/cakk/api/mapper/HeartMapper.java
  cakk-api/src/main/java/com/cakk/api/mapper/LinkMapper.java
  cakk-api/src/main/java/com/cakk/api/mapper/PointMapper.java
  cakk-api/src/main/java/com/cakk/api/mapper/ShopMapper.java
  cakk-api/src/main/java/com/cakk/api/mapper/ShopOperationMapper.java
  cakk-api/src/main/java/com/cakk/api/mapper/UserMapper.java
  cakk-api/src/main/java/com/cakk/api/provider/oauth/PublicKeyProvider.java
  cakk-api/src/main/java/com/cakk/api/provider/oauth/impl/AppleAuthProvider.java
  cakk-api/src/main/java/com/cakk/api/provider/oauth/impl/GoogleAuthProvider.java
  cakk-api/src/main/java/com/cakk/api/provider/oauth/impl/KakaoAuthProvider.java
  cakk-api/src/main/java/com/cakk/api/resolver/AuthorizedUserResolver.java
  cakk-api/src/main/java/com/cakk/api/resolver/RefreshTokenResolver.java
  cakk-api/src/main/java/com/cakk/api/service/cake/CakeService.java
  cakk-api/src/main/java/com/cakk/api/service/like/HeartService.java
  cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
  cakk-api/src/main/java/com/cakk/api/service/user/SignService.java
  cakk-api/src/main/java/com/cakk/api/validator/OperationValidator.java
  cakk-api/src/test/java/com/cakk/api/service/like/HeartServiceTest.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/bo/CakeShops.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/converter/DayOfWeekConverter.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/converter/LinkKindConverter.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/cake/Cake.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/cake/CakeCategory.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/shop/CakeShop.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/shop/CakeShopLink.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/shop/CakeShopOperation.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/user/BusinessInformation.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeHeartQueryRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeQueryRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeShopOperationQueryRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeShopQueryRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeTagQueryRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/BusinessInformationReader.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeCategoryReader.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeReader.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeShopLinkReader.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeShopReader.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeTagReader.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/TagReader.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/UserReader.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/writer/BusinessInformationWriter.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/writer/CakeShopWriter.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/writer/CakeWriter.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/writer/TagWriter.java
Labels: refactor

#152 Feature: 로그아웃 기능 구현
  cakk-api/src/main/java/com/cakk/api/annotation/AccessToken.java
  cakk-api/src/main/java/com/cakk/api/config/SecurityConfig.java
  cakk-api/src/main/java/com/cakk/api/config/WebMvcConfig.java
  cakk-api/src/main/java/com/cakk/api/controller/user/SignController.java
  cakk-api/src/main/java/com/cakk/api/provider/jwt/JwtProvider.java
  cakk-api/src/main/java/com/cakk/api/resolver/AccessTokenResolver.java
  cakk-api/src/main/java/com/cakk/api/service/user/SignService.java
  cakk-api/src/test/java/com/cakk/api/common/base/IntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/integration/user/SignIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/provider/JwtProviderTest.java
  cakk-api/src/test/java/com/cakk/api/service/user/SignServiceTest.java
  cakk-common/src/main/java/com/cakk/common/enums/ReturnCode.java
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/TokenRedisRepository.java
Labels: feature

#156 Chore: jacoco 설정
  build.gradle
  lombok.config
Labels: chore

#160 Refactor | #159 | @lcomment | SpEL을 활용한 Lock Key 리팩토링
  cakk-api/src/main/java/com/cakk/api/annotation/DistributedLock.java
  cakk-api/src/main/java/com/cakk/api/aspect/DistributedLockAspect.java
  cakk-api/src/main/java/com/cakk/api/service/like/HeartService.java
  cakk-api/src/main/java/com/cakk/api/service/like/LikeService.java
  cakk-api/src/main/java/com/cakk/api/utils/CustomSpringExpressionLanguageParser.java
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/dto/param/ExecuteWithLockParam.java
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/LockRedisRepository.java
Labels: refactor

#167 Deploy: 2.0.2.1
  cakk-api/src/main/java/com/cakk/api/dto/request/shop/SearchShopByLocationRequest.java
  cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
  cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeQueryRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeShopQueryRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeShopReader.java
Labels: deploy

#169 Refactor: 케이크샵 사장님 인증 요청 로직 리팩토링
  cakk-api/src/main/java/com/cakk/api/config/CertificationTemplateConfig.java
  cakk-api/src/main/java/com/cakk/api/listener/CertificationEventListener.java
  cakk-api/src/main/java/com/cakk/api/mapper/EventMapper.java
  cakk-api/src/main/java/com/cakk/api/service/slack/SlackService.java
  cakk-api/src/main/java/com/cakk/api/template/CertificationTemplate.java
  cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
  cakk-api/src/test/resources/sql/insert-cake-shop.sql
  cakk-domain/mysql/src/test/java/com/cakk/domain/entity/user/BusinessInformationTest.java
  cakk-external/build.gradle
  cakk-external/src/main/java/com/cakk/external/executor/CertificationApiExecutor.java
  cakk-external/src/main/java/com/cakk/external/executor/CertificationSlackApiExecutor.java
  cakk-external/src/main/java/com/cakk/external/extractor/CertificationMessageExtractor.java
  cakk-external/src/main/java/com/cakk/external/extractor/CertificationSlackMessageExtractor.java
  cakk-external/src/main/java/com/cakk/external/vo/CertificationMessage.java
Labels: refactor

#173 Deploy: v2.0.2.2 배포
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/config/RedisConfig.java
Labels: deploy

#174 Deploy: v2.0.2.2
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/config/RedisConfig.java
Labels: deploy

#175 Deploy: 2.0.0.2 배포
  cakk-api/src/test/java/com/cakk/api/common/container/RedisTestContainer.java
Labels: deploy
