Repository CAKK-DEV/cakk-server, pull requests merged in 2024-08, with the labels that each got.

#177 Fix: 이메일 전송 로직 수정
  cakk-external/src/main/java/com/cakk/external/config/MailConfig.java
  cakk-external/src/main/java/com/cakk/external/service/MailService.java
Labels: fix

#179 Fix: 케이크 샵 검색 시, 페이지네이션이 이루어지지 않은 부분 수정 및 JPA 최적화
  cakk-api/src/main/resources/application.yml
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeShopQueryRepository.java
Labels: fix

#180 Refactor: 어드민 모듈 생성 및 kotlin dsl 리팩토링
  build.gradle
  build.gradle.kts
  cakk-admin/build.gradle.kts
  cakk-api/build.gradle
  cakk-api/src/test/java/com/cakk/api/ArchitectureTest.java
  cakk-api/src/test/java/com/cakk/api/common/annotation/MockCustomUser.java
  cakk-api/src/test/java/com/cakk/api/common/base/IntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/common/base/MockMvcTest.java
  cakk-api/src/test/java/com/cakk/api/common/base/MockitoTest.java
  cakk-api/src/test/java/com/cakk/api/common/utils/TestUtils.java
  cakk-api/src/test/java/com/cakk/api/controller/AwsS3ControllerTest.java
  cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/integration/user/HeartIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/provider/GoogleAuthProviderTest.java
  cakk-api/src/test/java/com/cakk/api/service/cake/CakeServiceTest.java
  cakk-api/src/test/java/com/cakk/api/service/shop/ShopServiceTest.java
  cakk-domain/mysql/src/test/java/com/cakk/domain/entity/user/BusinessInformationTest.java
  gradle.properties
  settings.gradle
  settings.gradle.kts
Labels: refactor

#181 Deploy | CAKK-32 | v2.0.3 배포
  build.gradle
  build.gradle.kts
  cakk-admin/build.gradle.kts
  cakk-api/build.gradle
  cakk-api/src/main/resources/application.yml
  cakk-api/src/test/java/com/cakk/api/ArchitectureTest.java
  cakk-api/src/test/java/com/cakk/api/common/annotation/MockCustomUser.java
  cakk-api/src/test/java/com/cakk/api/common/base/IntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/common/base/MockMvcTest.java
  cakk-api/src/test/java/com/cakk/api/common/base/MockitoTest.java
  cakk-api/src/test/java/com/cakk/api/common/utils/TestUtils.java
  cakk-api/src/test/java/com/cakk/api/controller/AwsS3ControllerTest.java
  cakk-api/src/test/java/com/cakk/api/integration/cake/CakeIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/integration/user/HeartIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/provider/GoogleAuthProviderTest.java
  cakk-api/src/test/java/com/cakk/api/service/cake/CakeServiceTest.java
  cakk-api/src/test/java/com/cakk/api/service/shop/ShopServiceTest.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeShopQueryRepository.java
  cakk-domain/mysql/src/test/java/com/cakk/domain/entity/user/BusinessInformationTest.java
  cakk-external/src/main/java/com/cakk/external/config/MailConfig.java
  cakk-external/src/main/java/com/cakk/external/service/MailService.java
  gradle.properties
  settings.gradle
  settings.gradle.kts
Labels: deploy

#183 Feature: 케이크샵 인증 요청 리스트 API 개발
  cakk-api/src/main/java/com/cakk/api/controller/shop/AdminController.java
  cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
  cakk-api/src/main/java/com/cakk/api/dto/param/operation/OwnerCandidateParam.java
  cakk-api/src/main/java/com/cakk/api/dto/response/shop/CakeShopOwnerCandidateResponse.java
  cakk-api/src/main/java/com/cakk/api/mapper/BusinessInformationMapper.java
  cakk-api/src/main/java/com/cakk/api/mapper/CakeDesignCategoryMapper.java
  cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
  cakk-api/src/test/java/com/cakk/api/integration/admin/AdminIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/service/shop/ShopServiceTest.java
  cakk-api/src/test/resources/sql/insert-business-information.sql
  cakk-common/src/main/java/com/cakk/common/enums/VerificationStatus.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/bo/user/DefaultVerificationPolicy.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/bo/user/VerificationPolicy.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/converter/VerificationStatusConverter.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/shop/CakeShop.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/user/BusinessInformation.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/user/User.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/jpa/BusinessInformationJpaRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/BusinessInformationReader.java
  cakk-domain/mysql/src/test/java/com/cakk/domain/base/DomainTest.java
  cakk-domain/mysql/src/test/java/com/cakk/domain/entity/user/BusinessInformationTest.java
  cakk-domain/mysql/src/test/java/com/cakk/domain/entity/user/VerificationPolicyTest.java
Labels: feature

#184 Feature: 사장님 인증 요청 상세 내용 조회 API 개발
  cakk-api/src/main/java/com/cakk/api/controller/shop/AdminController.java
  cakk-api/src/main/java/com/cakk/api/dto/response/shop/CakeShopOwnerCandidateResponse.java
  cakk-api/src/main/java/com/cakk/api/dto/response/shop/CakeShopOwnerCandidatesResponse.java
  cakk-api/src/main/java/com/cakk/api/mapper/BusinessInformationMapper.java
  cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
  cakk-api/src/test/java/com/cakk/api/integration/admin/AdminIntegrationTest.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/jpa/BusinessInformationJpaRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/BusinessInformationReader.java
Labels: feature

#185 Deploy | CAKK-33 | v2.0.3 배포
  cakk-api/src/main/java/com/cakk/api/controller/shop/AdminController.java
  cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
  cakk-api/src/main/java/com/cakk/api/dto/param/operation/OwnerCandidateParam.java
  cakk-api/src/main/java/com/cakk/api/dto/response/shop/CakeShopOwnerCandidateResponse.java
  cakk-api/src/main/java/com/cakk/api/dto/response/shop/CakeShopOwnerCandidatesResponse.java
  cakk-api/src/main/java/com/cakk/api/mapper/BusinessInformationMapper.java
  cakk-api/src/main/java/com/cakk/api/mapper/CakeDesignCategoryMapper.java
  cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
  cakk-api/src/test/java/com/cakk/api/integration/admin/AdminIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/service/shop/ShopServiceTest.java
  cakk-api/src/test/resources/sql/insert-business-information.sql
  cakk-common/src/main/java/com/cakk/common/enums/VerificationStatus.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/bo/user/DefaultVerificationPolicy.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/bo/user/VerificationPolicy.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/converter/VerificationStatusConverter.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/shop/CakeShop.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/user/BusinessInformation.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/user/User.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/jpa/BusinessInformationJpaRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/BusinessInformationReader.java
  cakk-domain/mysql/src/test/java/com/cakk/domain/base/DomainTest.java
  cakk-domain/mysql/src/test/java/com/cakk/domain/entity/user/BusinessInformationTest.java
  cakk-domain/mysql/src/test/java/com/cakk/domain/entity/user/VerificationPolicyTest.java
Labels: deploy

#188 Refactor | CAKK-40 | BusinessInformation 관련 기능 이관
  cakk-admin/src/main/kotlin/com/cakk/admin/annotation/OperationDay.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/controller/BusinessInformationController.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/param/ShopLinkParam.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/request/CreateShopRequest.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/request/PromotionRequest.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/response/CakeShopCreateResponse.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/mapper/BusinessInformationMapper.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/mapper/LinkMapper.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/mapper/PointMapper.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/mapper/ShopMapper.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/service/BusinessInformationService.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/service/ShopService.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/validator/OperationValidator.kt
  cakk-admin/src/main/resources/application-local.yml
  cakk-admin/src/main/resources/application.yml
Labels: refactor

#189 Refactor: 케이크 샵 인증 요청 로직 개선
  cakk-api/src/main/java/com/cakk/api/dto/request/user/CertificationRequest.java
  cakk-api/src/main/java/com/cakk/api/mapper/ShopMapper.java
  cakk-api/src/main/java/com/cakk/api/service/shop/ShopService.java
  cakk-api/src/test/java/com/cakk/api/integration/shop/ShopIntegrationTest.java
  cakk-api/src/test/java/com/cakk/api/service/shop/ShopServiceTest.java
  cakk-api/src/test/resources/sql/insert-business-information.sql
  cakk-api/src/test/resources/sql/insert-cake-shop.sql
  cakk-api/src/test/resources/sql/insert-cake.sql
  cakk-api/src/test/resources/sql/insert-heart-for-concurrency-test.sql
  cakk-api/src/test/resources/sql/insert-like-for-concurrency-test.sql
  cakk-common/src/main/java/com/cakk/common/enums/ReturnCode.java
  cakk-common/src/main/java/com/cakk/common/enums/Role.java
  cakk-common/src/main/java/com/cakk/common/enums/VerificationStatus.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/bo/user/DefaultVerificationPolicy.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/bo/user/VerificationPolicy.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/shop/CakeShop.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/user/BusinessInformation.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/user/User.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/mapper/EventMapper.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/jpa/BusinessInformationJpaRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeQueryRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeShopQueryRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeShopReader.java
  cakk-domain/mysql/src/test/java/com/cakk/domain/base/DomainTest.java
  cakk-domain/mysql/src/test/java/com/cakk/domain/entity/user/BusinessInformationTest.java
  cakk-domain/mysql/src/test/java/com/cakk/domain/entity/user/VerificationPolicyTest.java
Labels: refactor

#190 Refactor | CAKK-42 | Cake 관련 기능 이관
  .gitignore
  cakk-admin/src/main/kotlin/com/cakk/admin/controller/BusinessInformationController.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/controller/CakeController.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/param/CakeCreateByAdminParam.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/param/CakeShopCreateByAdminParam.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/param/CakeUpdateByAdminParam.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/request/CakeCreateByAdminRequest.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/request/CakeShopCreateByAdminRequest.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/request/CakeUpdateByAdminRequest.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/response/TagResponse.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/mapper/BusinessInformationMapper.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/mapper/CakeDesignCategoryMapper.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/mapper/CakeMapper.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/mapper/ShopMapper.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/service/BusinessInformationService.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/service/CakeService.kt
Labels: refactor

#191 Refactor | CAKK-41 | 케이크 샵 관련 기능 이관
  .editorconfig
  cakk-admin/src/main/kotlin/com/cakk/admin/controller/BusinessInformationController.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/controller/ShopController.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/request/AddressUpdateByAdminRequest.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/request/CakeShopUpdateByAdminRequest.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/request/LinkUpdateByAdminRequest.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/dto/request/ShopOperationUpdateByAdminRequest.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/mapper/LinkMapper.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/mapper/ShopOperationMapper.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/service/BusinessInformationService.kt
  cakk-admin/src/main/kotlin/com/cakk/admin/service/ShopService.kt
  cakk-api/src/main/java/com/cakk/api/dto/request/shop/UpdateShopRequest.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/link/UpdateLinkParam.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/operation/UpdateShopOperationParam.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/shop/CakeShopUpdateParam.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/dto/param/shop/UpdateShopAddressParam.java
Labels: refactor

#193 Refactor | CAKK-54 | 케이크 하트 기능 리팩토링
  cakk-api/src/main/java/com/cakk/api/service/like/HeartService.java
  cakk-api/src/test/java/com/cakk/api/service/like/HeartServiceTest.java
  cakk-api/src/test/resources/sql/insert-cake.sql
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/cake/Cake.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/user/User.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/mapper/CakeHeartMapper.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeQueryRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeHeartReader.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeReader.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/writer/CakeHeartWriter.java
Labels: refactor

#194 Refactor | CAKK-55 | 케이크샵 하트 및 기대돼요 기능 리팩토링
  .github/workflows/ci.yml
  cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
  cakk-api/src/main/java/com/cakk/api/service/like/HeartService.java
  cakk-api/src/main/java/com/cakk/api/service/like/LikeService.java
  cakk-api/src/test/java/com/cakk/api/service/like/HeartServiceTest.java
  cakk-api/src/test/java/com/cakk/api/service/like/LikeServiceTest.java
  cakk-api/src/test/resources/sql/insert-cake-shop.sql
  cakk-domain/mysql/build.gradle
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/annotation/DomainFacade.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/cake/Cake.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/shop/CakeShop.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/user/User.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/facade/user/UserHeartFacade.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/facade/user/UserLikeFacade.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/mapper/CakeShopHeartMapper.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/mapper/CakeShopLikeMapper.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeShopQueryRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeShopReader.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/writer/CakeShopHeartWriter.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/writer/CakeShopLikeWriter.java
  cakk-domain/mysql/src/test/java/com/cakk/domain/base/DomainTest.java
  cakk-domain/mysql/src/test/java/com/cakk/domain/facade/user/UserHeartFacadeTest.java
  cakk-domain/mysql/src/test/java/com/cakk/domain/facade/user/UserLikeFacadeTest.java
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/CakeShopViewsRedisRepository.java
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/CakeViewsRedisRepository.java
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/EmailVerificationRedisRepository.java
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/KeywordRedisRepository.java
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/TokenRedisRepository.java
Labels: refactor

#195 Deploy | CAKK-56 | v2.0.4 배포
  .github/workflows/ci.yml
  cakk-api/src/main/java/com/cakk/api/controller/shop/ShopController.java
  cakk-api/src/main/java/com/cakk/api/service/like/HeartService.java
  cakk-api/src/main/java/com/cakk/api/service/like/LikeService.java
  cakk-api/src/test/java/com/cakk/api/service/like/HeartServiceTest.java
  cakk-api/src/test/java/com/cakk/api/service/like/LikeServiceTest.java
  cakk-api/src/test/resources/sql/insert-cake-shop.sql
  cakk-api/src/test/resources/sql/insert-cake.sql
  cakk-domain/mysql/build.gradle
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/annotation/DomainFacade.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/cake/Cake.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/shop/CakeShop.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/entity/user/User.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/facade/user/UserHeartFacade.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/facade/user/UserLikeFacade.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/mapper/CakeHeartMapper.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/mapper/CakeShopHeartMapper.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/mapper/CakeShopLikeMapper.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeQueryRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/query/CakeShopQueryRepository.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeHeartReader.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeReader.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/reader/CakeShopReader.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/writer/CakeHeartWriter.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/writer/CakeShopHeartWriter.java
  cakk-domain/mysql/src/main/java/com/cakk/domain/mysql/repository/writer/CakeShopLikeWriter.java
  cakk-domain/mysql/src/test/java/com/cakk/domain/base/DomainTest.java
  cakk-domain/mysql/src/test/java/com/cakk/domain/facade/user/UserHeartFacadeTest.java
  cakk-domain/mysql/src/test/java/com/cakk/domain/facade/user/UserLikeFacadeTest.java
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/CakeShopViewsRedisRepository.java
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/CakeViewsRedisRepository.java
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/EmailVerificationRedisRepository.java
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/KeywordRedisRepository.java
  cakk-domain/redis/src/main/java/com/cakk/domain/redis/repository/TokenRedisRepository.java
Labels: deploy

#198 Refactor | CAKK-59 | External 모듈 리팩토링 및 Send 관련 추상화
  build.gradle.kts
  cakk-api/build.gradle
  cakk-api/build.gradle.kts
  cakk-api/src/main/java/com/cakk/api/config/CertificationTemplateConfig.java
  cakk-api/src/main/java/com/cakk/api/config/SlackWebhookConfig.java
  cakk-api/src/main/java/com/cakk/api/config/VerificationCodeSendTemplateConfig.java
  cakk-api/src/main/java/com/cakk/api/listener/CertificationEventListener.java
  cakk-api/src/main/java/com/cakk/api/listener/EmailSendEventListener.java
  cakk-api/src/main/java/com/cakk/api/mapper/EventMapper.java
  cakk-api/src/main/java/com/cakk/api/template/CertificationTemplate.java
  cakk-api/src/test/java/com/cakk/api/listener/EmailSendEventListenerTest.java
  cakk-external/build.gradle
  cakk-external/build.gradle.kts
  cakk-external/src/main/java/com/cakk/external/config/EmailConfig.kt
  cakk-external/src/main/java/com/cakk/external/config/MailConfig.java
  cakk-external/src/main/java/com/cakk/external/config/SlackWebhookConfig.kt
  cakk-external/src/main/java/com/cakk/external/extractor/CertificationSlackMessageExtractor.java
  cakk-external/src/main/java/com/cakk/external/extractor/VerificationCodeMessageExtractor.kt
  cakk-external/src/main/java/com/cakk/external/extractor/VerificationCodeMimeMessageExtractor.kt
  cakk-external/src/main/java/com/cakk/external/sender/EmailSender.kt
  cakk-external/src/main/java/com/cakk/external/sender/MessageSender.kt
  cakk-external/src/main/java/com/cakk/external/sender/SlackMessageSender.kt
  cakk-external/src/main/java/com/cakk/external/service/MailService.java
  cakk-external/src/main/java/com/cakk/external/template/CertificationTemplate.kt
  cakk-external/src/main/java/com/cakk/external/template/VerificationCodeSendTemplate.kt
  cakk-external/src/main/java/com/cakk/external/vo/VerificationMessage.kt
Labels: feature, refactor

#201 Refactor | CAKK-61 | DIP 위반 문제 해결
  cakk-api/build.gradle.kts
  cakk-api/src/main/java/com/cakk/api/config/MessageTemplateConfig.java
  cakk-external/src/main/java/com/cakk/external/extractor/VerificationCodeMimeMessageExtractor.kt
  cakk-external/src/main/java/com/cakk/external/sender/EmailMessageSender.kt
  cakk-external/src/main/java/com/cakk/external/sender/SlackMessageSender.kt
Labels: refactor

#202 Deploy | CAKK-61 | v.2.0.4 배포
  cakk-api/build.gradle.kts
  cakk-api/src/main/java/com/cakk/api/config/MessageTemplateConfig.java
  cakk-external/src/main/java/com/cakk/external/extractor/VerificationCodeMimeMessageExtractor.kt
  cakk-external/src/main/java/com/cakk/external/sender/EmailMessageSender.kt
  cakk-external/src/main/java/com/cakk/external/sender/SlackMessageSender.kt
Labels: refactor
